### ISSUE TITLE
Sorting of transaction outputs prevents from knowing the index of the output you just created

### ISSUE THREAD

**Issue by lunfardo314** [iotaledger/goshimmer#1012]
## Description

Index of output is important in some use cases. For example I want to keep #0 and #1 inputs always for specific use of the ISCP chain. 

## Motivation

With enforced sorting of it we do not control the index. Not being able to know the index we:
- cannot use specific indices with specific meaning for the use case. 
- we don't know the color of the minted tokens immediately after the transaction if fully formed
It all makes it very cumbersome to work with it.

Note, that sorting is not needed for determinism because we supply outputs as slice, the fixed order of it.

## Requirements

1. use outputs in the order supplied by the user 
2.  provide functions to prevent duplicates separately or as a part of validation

## Open questions (optional)

None

## Are you planning to do it yourself in a pull request?

No

**Comment by lunfardo314** [comment]
it seems outputs are sorted due to compatibility with Chrysalis. The solution would be to keep track of how the indices are sorted. However:
1. it seems two outputs with exactly the same address and colored balances are considered to be duplicates (identical `ObjectStorageValue()` ). It does not seem to be correct as there's not reasonable semantic rule which prevents us from putting two or more identical outputs into the transaction for whatever reason. In ISCP it e.g. prevents from sending 2 different requests to 2 different smart contracts both with 5 iotas attached to the same chain .    
2. it would be good to take the sorting out in the separate function, in order to avoid redundancy in serialization and sorting

**Comment by hmoog** [comment]
I agree that having two Outputs that are similar should not be a duplicate. We will change that - but making the sorting a separate function is IMHO a bad idea because the API should not allow to create invalid transactions.

**Comment by Wollac** [comment]
What does "similar" mean? Are they (serialized) byte to byte equal or not?

If they are really 100% equal, it does seem very strange to me, why it would be desirable to do that.
In Chrysalis we currently even have the stronger requirement that each address can only be used once in a transaction. However, it is not 100% clear how this will change for colored coins...

**Comment by lunfardo314** [comment]
- rule of "duplicates" seems to me artificial. Why we consider two outputs identical just because their serialized binary representation is identical? The only meaningful identity of output in transaction is its index.
- I do not see how enforced ordering contributes to determinism. It just erases (randomizes) valuable information we want to pass with the transaction: the exact indices of outputs. 
- `each address can only be used once in a transaction.` 
This is exactly what I was fighting against in earlier goshimmer. This made my current implementation (with one address in outputs) very complicated for no reason (need for colored coins, not easy metadata etc). That rule makes it very difficult to implement special output types for opcodes and L1 support for smart contracts and other use cases.

IMO we should see each output as a command to the ledger with attached tokens. It is up to the user what commands to put. Dust problem can only be solved by enforcing mandatory cost to each output

**Comment by Wollac** [comment]
Your are misunderstanding my point:
In the UTXO model a transaction is defined UtxoTx := (I, O) where I is as a _set_ of inputs (i.e. references of outputs it consumes) and O is a _set_ of outputs. That's everything needed to compute the ledger state. As such the order of inputs/outputs does not matter. From an implementation PoV, however, a set does not have a deterministic order and as such, it is necessary to define an ordering of the inputs/outputs such that the same UtxoTx always leads to the same sequence of bytes on all platforms.
When designing the protocol, we chose to integrate that into the core protocol as this prevents accidental misuse and poses by far the clearest implementation, especially under the space-constrained limitations we are usually assuming for IOTA. Bitcoin, for example, has [BIP-69](https://github.com/bitcoin/bips/blob/master/bip-0069.mediawiki) that defines exactly that. However, it came later and is only implemented on the transaction issuer (wallet) level, while we had the chance to integrate that into the protocol from the beginning.

You are trying to abuse the order of inputs/outputs, such that suddenly two byte sequences that correspond to the same UtxoTx are treated differently. This is no longer compatible with the UTXO. To still be able to model equivalent behavior we have meta data, i.e. ExUtxoTx := (I, O, M) and you can now have two distinct transactions t = (I, O, M) and t'= (I, O, M') corresponding to the same sets I and O. The MetaData-UTXO model is strictly more powerful than using, what you are proposing, indexed families for I, O: Everything you can do with indexed-UTXO, you can do with MetaData-UTXO.
Obviously, this does not mean that indexed-UTXO is not a powerful or convenient concept, but it does mean that we should really think twice before making such an mathematically redundant core protocol change! Maybe there are other clever options in addition to trivial meta data usage.

The argument that `each address can only be used once in a transaction`, has nothing to do with that, though! It is not part of the UTXO model, but instead was an idea of some kind of "dust protection". As such, it is only per output type (although we only have one in the beginning) and much much weaker requirement. 
What exactly are you formally hoping to achieve when the "one address" restriction is lifted? And output-metdata alone is not an argument as this can trivially be also achieved with tx-metadata...

**Comment by hmoog** [comment]
If you want to mint two coins within the same transaction then the two outputs that create those coins would have the exact same serialized format but would receive different colors when they are booked as the color depends on the OutputID.

I can totally see situations where this might be something you want to do.

**Comment by Wollac** [comment]
> If you want to mint two coins within the same transaction then the two outputs that create those coins would have the exact same serialized format but would receive different colors when they are booked as the color depends on the OutputID.
I agree that would be an example. How important is it that such mints are atomic, i.e. in the same transaction, instead of in two separate transactions.
Anything else, especially in the context of "moving" or without colors? In theory, when you've created two outputs, they can be consumed by two transactions at the same time and not only sequentially. However, it seems to me that this is more of a mathematical distinction than anything of practical relevance.

The ordering can trivially be achieved by having a list of the desired indices in the meta data. While this would definitely not be good design in practice, it formally shows that having metadata is more powerful than ordered indices.

**Comment by lunfardo314** [comment]
I know how to implement it all with metadata, and it is already implemented exactly like that. 
However, it is cumbersome and I don't see ISCP as a "L2 use case" but rather a must part of the core concept (not here to discuss why). 
If you say ordering is a part of some kind of standard, I accept that, and lets go with it. 
Even I do not think defining my own order of outputs is abusing of anything or breaking determinism or something. It comes to the point ` where I is as a **set**`, why it is a set I have no idea, because set does not have deterministic order and that is why **set** is an artificial construct in computing. The natural one is a list. But maybe standard is more clever than me. So, let it be, the artificial order is not a showstopper. 
The artificial binary identities and duplicate removal is much worse. The example above with minting shows it. But please do not limit your thinking about "wallet/asset" use cases, there are many other reasons why I may need to send identical collection of tokens in the same transaction and likely to the same address. With duplicate removal (and with current output types) the metadata does not help. So, current implementation (with current output types) is a showstopper for ISCP.

Very important "dust protection" by very artificial "one output address in transaction" rule. It is the reason why I was forced to use colored coins to track backlog of requests in the current implementation (because in the old Goshimmer was only one address among inputs). It works but it is a very hacky way and I want to get rid of it in the new version. With current tx structure in Goshimmer I can do that because outputs has indices, but that duplicate removal thingy spoils it. I think "one output address in transaction" must be removed from Chrysalis. Dust protection must be done differently.

The solution I am promoting now is about implementing 2 special output types which will be used by ISCP and in use case such as "golden coin". With this solution a) ISCP will be 100% orthogonal to colored coins, b) all request metadata will be attached directly output, so no need for transaction level metadata at all and c) there's no need to change sorting/duplicate removal how it is implemented now (because metadata will be part of binary identity). There are already draft spec and Levi is working on it

**Comment by hmoog** [comment]
`How important is it that such mints are atomic, i.e. in the same transaction, instead of in two separate transactions.`

It really depends on the use case. Especially with NFT's it is often the case that you for example create multiple NFT's with different rarities as part of a collection of similar items (art, ingame items and so on.).

Let's say you want to create NFT's that represents a set of weapons in an MMO and there are:

- 5 Weapon that are are "Legendary" (exist only a single time)
- 5 Weapons that are "Epic" (exist 100 times)
- 10 Weapons that are "Rare" (exist 1000 times)
- 100 Weapons that are "Common" (exist 100000 times)

If you would allow all of these tokens to be created in a single atomic transaction then you could for example create 5 outputs with a single minted coin to represent the legendary items which would be identical on the byte level but result in differently colored tokens in the ledger.

Since the color depends on the OutputID which starts with the TransactionID, all items could immediately be identified to belong to the same "set" without having to use a 2nd layer "registry" to tie the set together. The color alone would be enough to identify all items of the given set.

There are other examples in DeFi where things need to happen atomically but I guess this example is enough.

**Comment by Wollac** [comment]
@lunfardo314
GoShimmer is not a protocol! It contains various bits and ideas, but does not claim to be final or complete in any way! So please do not consider it any kind of reference or make any serious architecture decisions around it, or when you do be ready to change everything again.
Chrysalis on the other hand _is_ a protocol and tries to make those claims. However, it does not contain any concepts about colored coins or similar so the premises are different. Here for example, limiting "one output address in transaction" as a dust protection is a reasonable step. Introducing colored coins poses a breaking change to the protocol and this obviously entails revisiting the previous dust protection and adapting it when meaningful.

> With duplicate removal (and with current output types) the metadata does not help. So, current implementation (with current output types) is a showstopper for ISCP.

Why do you think so? Why is it for your use-case, for example, not sufficient to just put the de-duplicated output information in the meta-data? As I've mentioned above it is true that allowing duplicates is conceptually slightly more powerful than forbidding them, but when you make such hard statements you must be less hand-wavy than this.

I really, think we need to take a step back from the established approaches and get a better formal understanding of the requirements of ISCP that you see and then find concepts for this! For example, changing the dust-protection and allowing multiple outputs per address is a far less extensive change than introducing new output types. And the dust-protection was designed to be changed anyways when colored coins are introduced.

**Comment by Wollac** [comment]
@hmoog 
I get your point and that is an example. However, in that case you would need a registry anyway to link the arbitrary color to the actual weapon. So this indicates, that it might make sense to consider allowing NFTs to have some choosable payload because they are actually distinct objects.

If you have two 100% byte-identical outputs on the same address, they by definition have the same unlock-criteria and cannot behave differently upon unlocking. My point is that when those two objects are still supposed to be treated differently, it might be worth re-evaluating the design of your output types, maybe a simple adaption there could lead to an even better protocol.

**Comment by lunfardo314** [comment]
btw, colored tokens are just codes. The semantics of it, what makes it and assets is in unbreakably attached metadata. So, either we have registry of metadata on L1, or we have to put it into a smart contract.

**Comment by Wollac** [comment]
I think we all agreed that a clean ISCP solution should rather try to rely on other means than hacky usages of "colored coins" / "utxo encodings". That particular discussion will be continued in a different medium.
