### ISSUE TITLE
Add link to the GoShimmer docs

### ISSUE THREAD

**Issue by capossele** [iotaledger/goshimmer#1043]
- Wiki
- README

**Comment by flashguru-git** [comment]
@capossele 
I'd like to create PR with simple modification, would you please add me to the organization?

**Comment by capossele** [comment]
> @capossele
> I'd like to create PR with simple modification, would you please add me to the organization?

This is an open source project, as such, anyone is free to open a PR

**Comment by jkrvivian** [comment]
Close by #1147 and [wiki](https://github.com/iotaledger/goshimmer/wiki)
