### ISSUE TITLE
Update the readme for the v0.1.0 release

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/goshimmer#105]
* Describes the different branches on the repository and what the represent/investigate.
* Link to the autopeering and FPC sim repository
* Setting up a development environment
* Install instructions and config example
* Contribution guide and a section with avatars of users which have contributed

**Comment by Wollac** [comment]
To be consistent with the executable name created by GoReleaser, it should be changed to `goshimmer` from `shimmer`
