### ISSUE TITLE
Introduce `Address()` method in `Signature` interface

### ISSUE THREAD

**Issue by lunfardo314** [iotaledger/goshimmer#1060]
Motivation: easier to determine sender(s) of the transaction
https://github.com/iotaledger/goshimmer/blob/51bac590a1ede988ecad3a24d618990005820455/packages/ledgerstate/signature.go#L43

**Comment by hmoog** [comment]
You can not generically derive the Address from a signature for all signature schemes. There are schemes like WOTS for example that are not based on Elliptic Curve Cryptography and where something like that is not possible.

We could however introduce an interface called EllipticCurveSignature or sth like that which would allow you to sth like:

```go
type EllipticCurveSignature interface {
    Signature
    Address() Address
}

switch typedSignature := signature.(type) {
case EllipticCurveSignature:
    fmt.Println(typedSignature.Address())
default:
    fmt.Prinltn("unsupported signature type")
}
```

The question however is if this additional type switch does add significant advantages over something like:

switch typedSignature := signature.(type) {
case *ED25519Address:
    fallthrough
case *BLSAddress:
    fmt.Println(typedSignature.Address())
default:
    fmt.Prinltn("unsupported signature type")
}
