### ISSUE TITLE
Stopping Docker container corrupts database

### ISSUE THREAD

**Issue by JanOonk** [iotaledger/goshimmer#1063]
## Bug description

Stopping a container (gracefully), and then restarting it again fails with an error about corrupted database. It will automatically restarts and fails again etc..

## GoShimmer version

v0.5

## Hardware specification

Synology DS702+ 
DSM 6.2.3-25426 Update 3
8GB RAM
Docker version 18.09.8, build bfed4f5

## Steps To reproduce the bug

1. Create a GoShimmer container based on iotaledger/goshimmer:latest
2. Start it
3. After a little while stop it gracefully
4. Restart

It will fail with an corrupted database error.

## Expected behaviour

It should of course just start normally.

## Actual behaviour

Corrupted database, and container keeps restarting.

## Errors

I can reproduce 100%. I have attached the log files for two times I tried recreating the container from scratch and deleting the database.
[logfiles.zip](https://github.com/iotaledger/goshimmer/files/6136897/logfiles.zip)

Could it be that the shutdown process doesn't wait long enough for the database garbage collection (or any other database related process) to finish which in turn leaves the database in a corrupted state?

**Comment by NiC0x36** [comment]
I had the same issue yesterday evening with Ubuntu 20.04, Docker version 20.10.5 on a CX21 Hetzner instance.

**Comment by jonastheis** [comment]
If you run GoShimmer with the provided `docker-compose.yml` then I've just opened a PR that should fix it #1064.

If you run it manually with Docker then you'll have to tell Docker to not send a SIGKILL after 10 seconds (which is the default) if the container is not yet shutdown. You can do that with e.g. `docker stop -t 60` as described in the [Docker docs](https://docs.docker.com/engine/reference/commandline/stop/#options)

**Comment by JanOonk** [comment]
Just for reference: that did the trick. I shelled into my NAS with putty and ran:
`sudo docker stop -t 60 containerID`

As you can seen in attached log:
Database garbage collection took 17 seconds and total time to shut down was 26 seconds! So that explains the corrupted database since it was still running after the default 10 sec shutdown.

[errorlog.zip](https://github.com/iotaledger/goshimmer/files/6137488/errorlog.zip)
