### ISSUE TITLE
Not syncing

### ISSUE THREAD

**Issue by creps** [iotaledger/goshimmer#1072]
## Bug description

When I start goshimmer, after a few seconds the Log generates an error and stops synchronizing the node. Neighbors are still accepted but no transactions are synchronized.

## GoShimmer version

0.5.1

## Hardware

8Cores
8Gb
50Gb SSD

## Steps To reproduce the bug

When I start goshimmer, after a few seconds the Log generates an error and stops synchronizing the node. Neighbors are still accepted but no transactions are synchronized.

## Expected behaviour

It should not give an error and should continue to synchronize transactions.

## Actual behaviour

Generates the following error in the log and stops synchronizing

## Errors

2021-03-15T15:54:59+01:00	ERROR	MessageLayer	node/plugin.go:74	message does not reference all the transaction's dependencies
github.com/iotaledger/hive.go/node.(*Plugin).LogError
	/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20210314220918-ac82b8322991/node/plugin.go:74
github.com/iotaledger/goshimmer/plugins/messagelayer.configure.func1
	/goshimmer/plugins/messagelayer/plugin.go:51
github.com/iotaledger/hive.go/events.ErrorCaller
	/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20210314220918-ac82b8322991/events/types.go:8
github.com/iotaledger/hive.go/events.(*Event).Trigger
	/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20210314220918-ac82b8322991/events/event.go:32
github.com/iotaledger/goshimmer/packages/tangle.(*Booker).Setup.func1
	/goshimmer/packages/tangle/booker.go:60
github.com/iotaledger/goshimmer/packages/tangle.MessageIDCaller
	/goshimmer/packages/tangle/tangle.go:176
github.com/iotaledger/hive.go/events.(*Event).Trigger
	/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20210314220918-ac82b8322991/events/event.go:32
github.com/iotaledger/goshimmer/packages/tangle.(*Scheduler).scheduleMessage.func1
	/goshimmer/packages/tangle/scheduler.go:106
github.com/iotaledger/goshimmer/packages/tangle.(*CachedMessageMetadata).Consume.func1
	/goshimmer/packages/tangle/message.go:1013
github.com/iotaledger/hive.go/objectstorage.(*CachedObjectImpl).Consume
	/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20210314220918-ac82b8322991/objectstorage/cached_object.go:132
github.com/iotaledger/goshimmer/packages/tangle.(*CachedMessageMetadata).Consume
	/goshimmer/packages/tangle/message.go:1012
github.com/iotaledger/goshimmer/packages/tangle.(*Scheduler).scheduleMessage
	/goshimmer/packages/tangle/scheduler.go:101
github.com/iotaledger/goshimmer/packages/tangle.(*Scheduler).run.func1
	/goshimmer/packages/tangle/scheduler.go:86

**Comment by jonastheis** [comment]
This should be fixed with #1075 and #1076.
