### ISSUE TITLE
Mana Dashboard detaches on browser refresh

### ISSUE THREAD

**Issue by alorraine** [iotaledger/goshimmer#1083]
## Bug description

With everything working and in sync, when I refresh my browser on page http://x.x.x.x:8081/mana, I get the warning `WARNING: Node not in sync, displayed mana values might be outdated!` and the page eventually crashes.

Rectified by clicking Dashboard on menu, then reentering by clicking Mana in menu. 'Back' in browser does not work. 

## GoShimmer version

0.5.2

## Hardware specification

Hetzner CX21
2 VCPU
4 GB RAM
40 GB DISK LOCAL

Google Chrome Version 89.0.4389.90 (Official Build) (x86_64)

## Steps To reproduce the bug

1. Refresh :8081/mana in Google Chrome
2. 
3. 

## Expected behaviour

Stats update, return to functional page

## Actual behaviour

Chart and node mana details go to zero. 

Access and Consensus Events do still update.

Page eventually crashes

## Errors
`Aw snap, something went wrong. Error code 6`

<img width="1138" alt="Screenshot 2021-03-17 at 12 45 09" src="https://user-images.githubusercontent.com/19776496/111469491-a9a71480-871e-11eb-94d4-04859baeb572.png">

**Comment by MyMonk089** [comment]
Got the same issue with Safari on Mac. Furthermore the site still seems to need much resources and is very slow. But very well done in case of displaying the Mana things!! Love it! :-)

**Comment by NiC0x36** [comment]
I have similar / the same issue. After crashing, I have to actually close the tab and reopen it then. Also Hetzner CX21.
