### ISSUE TITLE
Pollen wallet address generation error and disappearing funds

### ISSUE THREAD

**Issue by schumannity** [iotaledger/goshimmer#1084]
## Bug description

When sending transactions via the pollen wallet for each new transaction, a new receive address is generated and the old receive address becomes a spent address. After reaching index 20 (beginning with index 21) the new address is neither receive or spent. With this the balance also disappears, although still on old receive address (checked with node explorer).

## GoShimmer version

- GoShimmer version: 0.5.2
- Pollen wallet GUI version: 0.5.1

## Hardware specification

- Operating system: Ubuntu 20.04.2 LTS
- RAM: 16 GB
- Number of cores: 4 vCPU
- Device type: google cloud platform e2-standard-4

## Steps To reproduce the bug

Issue transactions through pollen wallet past index 20.

1. Create a new wallet
2. Request tokens from faucet
3. Consecutively issue 20 transactions with small amounts
4. Bug appears when 21th address is generated ("There are no balances in the wallet.")

## Expected behaviour

Static receive address with newly generated spent addresses, as well as continued wallet balance.

## Actual behaviour

Unexpected behavior in address generation and management.

## Errors

<img width="830" alt="Screen Shot 2021-03-17 at 13 49 10" src="https://user-images.githubusercontent.com/22917343/111469930-90ef2c80-8727-11eb-8376-fd1cff109dd5.png">

**Comment by jkrvivian** [comment]
Thanks for reporting, yet this issue does not appear in our latest release: GoShimmer v0.5.6 and Pollen wallet v0.5.3. 
Wallet functions properly until 25th transactions:
![image](https://user-images.githubusercontent.com/11289354/114333235-6784bd80-9b7a-11eb-9394-27d6c9d053fe.png)
