### ISSUE TITLE
Panic in HighestReferencedMarkers

### ISSUE THREAD

**Issue by capossele** [iotaledger/goshimmer#1090]
panic: Index(1521) is smaller than the lowest known Index
goroutine 88 [running]:
github.com/iotaledger/goshimmer/packages/markers.(*ParentReferences).HighestReferencedMarkers(0xc008b40000, 0x5f1, 0xc00fe92f30)
        /home/angelo.capossele/goshimmer/packages/markers/parent_references.go:160 +0x29f
github.com/iotaledger/goshimmer/packages/markers.(*Sequence).HighestReferencedParentMarkers(...)
        /home/angelo.capossele/goshimmer/packages/markers/sequence.go:107
github.com/iotaledger/goshimmer/packages/markers.(*Manager).normalizeMarkers.func2.1(0xc00d352ff0)
        /home/angelo.capossele/goshimmer/packages/markers/manager.go:282 +0x6c
github.com/iotaledger/goshimmer/packages/markers.(*CachedSequence).Consume.func1(0x1d396b8, 0xc00d352ff0)
        /home/angelo.capossele/goshimmer/packages/markers/sequence.go:230 +0x42
github.com/iotaledger/hive.go/objectstorage.(*CachedObjectImpl).Consume(0xc00c052320, 0xc00abc2a40, 0x0, 0x0, 0x0, 0xc004fa1100)
        /home/angelo.capossele/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20210314220918-ac82b8322991/objectstorage/cached_object.go:132 +0xda
github.com/iotaledger/goshimmer/packages/markers.(*CachedSequence).Consume(0xc015acb128, 0xc004fa1180, 0x0, 0x0, 0x0, 0xc00c052320)
        /home/angelo.capossele/goshimmer/packages/markers/sequence.go:229 +0x8b
github.com/iotaledger/goshimmer/packages/markers.(*Manager).normalizeMarkers.func2(0x1e, 0x5f1, 0xc015acb178)
        /home/angelo.capossele/goshimmer/packages/markers/manager.go:280 +0x14f
github.com/iotaledger/goshimmer/packages/markers.(*Markers).ForEach(0xc00fe92db0, 0xc015acb290, 0x1)
        /home/angelo.capossele/goshimmer/packages/markers/marker.go:260 +0x110
github.com/iotaledger/goshimmer/packages/markers.(*Manager).normalizeMarkers(0xc000322e80, 0xc00fe92a80, 0x0, 0xc00fe92a80)
        /home/angelo.capossele/goshimmer/packages/markers/manager.go:275 +0x2a5
github.com/iotaledger/goshimmer/packages/markers.(*Manager).InheritStructureDetails(0xc000322e80, 0xc004fa0ec0, 0x6, 0x8, 0x1b30ee0, 0xc015acb558, 0x0, 0x0, 0xc00c6627bc, 0xc00c6627bc)
        /home/angelo.capossele/goshimmer/packages/markers/manager.go:73 +0x165
github.com/iotaledger/goshimmer/packages/tangle.(*MarkersManager).InheritStructureDetails(0xc00023f8c0, 0xc011f783c0, 0xc015acb558, 0x0, 0x0, 0x95f1be7cd4080a01)
        /home/angelo.capossele/goshimmer/packages/tangle/booker.go:234 +0x9c
github.com/iotaledger/goshimmer/packages/tangle.(*Booker).Book.func1.1(0xc00c6626e0)
        /home/angelo.capossele/goshimmer/packages/tangle/booker.go:137 +0xd35
github.com/iotaledger/goshimmer/packages/tangle.(*CachedMessageMetadata).Consume.func1(0x1d398f8, 0xc00c6626e0)
        /home/angelo.capossele/goshimmer/packages/tangle/message.go:1013 +0x42
github.com/iotaledger/hive.go/objectstorage.(*CachedObjectImpl).Consume(0xc01187a280, 0xc0148d8cb0, 0x0, 0x0, 0x0, 0xc001beab00)
        /home/angelo.capossele/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20210314220918-ac82b8322991/objectstorage/cached_object.go:132 +0xda
github.com/iotaledger/goshimmer/packages/tangle.(*CachedMessageMetadata).Consume(0xc0148d8ca0, 0xc001beab40, 0x0, 0x0, 0x0, 0x0)
        /home/angelo.capossele/goshimmer/packages/tangle/message.go:1012 +0x8b
github.com/iotaledger/goshimmer/packages/tangle.(*Booker).Book.func1(0xc011f783c0)
        /home/angelo.capossele/goshimmer/packages/tangle/booker.go:88 +0x12a
github.com/iotaledger/goshimmer/packages/tangle.(*CachedMessage).Consume.func1(0x1d39898, 0xc011f783c0)
        /home/angelo.capossele/goshimmer/packages/tangle/message.go:600 +0x42
github.com/iotaledger/hive.go/objectstorage.(*CachedObjectImpl).Consume(0xc01187a320, 0xc0148d8c90, 0x0, 0x0, 0x0, 0xc001beaa00)
        /home/angelo.capossele/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20210314220918-ac82b8322991/objectstorage/cached_object.go:132 +0xda
github.com/iotaledger/goshimmer/packages/tangle.(*CachedMessage).Consume(0xc015acbbd8, 0xc001beaa80, 0x20)
        /home/angelo.capossele/goshimmer/packages/tangle/message.go:599 +0x7e
github.com/iotaledger/goshimmer/packages/tangle.(*Booker).Book(0xc000136940, 0xab631c6d9a3463e3, 0xc370c5a4b35b403d, 0x967b53521f02fdbc, 0x33d30ec282046dbb, 0x41101a, 0x12e0400)
        /home/angelo.capossele/goshimmer/packages/tangle/booker.go:87 +0x116
github.com/iotaledger/goshimmer/packages/tangle.(*Booker).Setup.func1(0xab631c6d9a3463e3, 0xc370c5a4b35b403d, 0x967b53521f02fdbc, 0x33d30ec282046dbb)
        /home/angelo.capossele/goshimmer/packages/tangle/booker.go:59 +0x47
github.com/iotaledger/goshimmer/packages/tangle.MessageIDCaller(0x1243500, 0xc00023f9f0, 0xc0148d8c70, 0x1, 0x1)
        /home/angelo.capossele/goshimmer/packages/tangle/tangle.go:178 +0x93
github.com/iotaledger/hive.go/events.(*Event).Trigger(0xc00026ff20, 0xc0148d8c70, 0x1, 0x1)
        /home/angelo.capossele/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20210314220918-ac82b8322991/events/event.go:32 +0x10b
github.com/iotaledger/goshimmer/packages/tangle.(*Scheduler).scheduleMessage.func1(0xc00c6626e0)
        /home/angelo.capossele/goshimmer/packages/tangle/scheduler.go:106 +0x169
github.com/iotaledger/goshimmer/packages/tangle.(*CachedMessageMetadata).Consume.func1(0x1d398f8, 0xc00c6626e0)
        /home/angelo.capossele/goshimmer/packages/tangle/message.go:1013 +0x42
github.com/iotaledger/hive.go/objectstorage.(*CachedObjectImpl).Consume(0xc01187a280, 0xc0148d8c60, 0x0, 0x0, 0x0, 0xc0179b2500)
        /home/angelo.capossele/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20210314220918-ac82b8322991/objectstorage/cached_object.go:132 +0xda
github.com/iotaledger/goshimmer/packages/tangle.(*CachedMessageMetadata).Consume(0xc0148d8c50, 0xc0179b25a0, 0x0, 0x0, 0x0, 0x0)
        /home/angelo.capossele/goshimmer/packages/tangle/message.go:1012 +0x8b
github.com/iotaledger/goshimmer/packages/tangle.(*Scheduler).scheduleMessage(0xc000303e60, 0xab631c6d9a3463e3, 0xc370c5a4b35b403d, 0x967b53521f02fdbc, 0x33d30ec282046dbb)
        /home/angelo.capossele/goshimmer/packages/tangle/scheduler.go:101 +0xfc
github.com/iotaledger/goshimmer/packages/tangle.(*Scheduler).run.func1(0xc000303e60)
        /home/angelo.capossele/goshimmer/packages/tangle/scheduler.go:86 +0x165
created by github.com/iotaledger/goshimmer/packages/tangle.(*Scheduler).run
        /home/angelo.capossele/goshimmer/packages/tangle/scheduler.go:80 +0x5c```
```

**Comment by MaKla89** [comment]
My node crashed with the same error message yesterday. Restart was only possible after deleting the database.
`panic: Index(1470) is smaller than the lowest known Index`

See log:
[Index_too_low.txt](https://github.com/iotaledger/goshimmer/files/6170188/Index_too_low.txt)

**Comment by MaKla89** [comment]
And again, this time with goshimmer v 0.5.3. This log is REVERSED:

[Index_too_low_053.txt](https://github.com/iotaledger/goshimmer/files/6212218/Index_too_low_053.txt)
