### ISSUE TITLE
messageWorkerPool full: packet message discarded

### ISSUE THREAD

**Issue by TeeVeeEss** [iotaledger/goshimmer#1096]
## Bug description

The public key of my node is 75g6r4tqGZhrgpDYZyZxVje1Qo54ezFYkCw94ELTLhPs, nodeId RifYaNfvVHu if you need that info for whatever reason :wink: It's up again (had to delete db) and trying to get synced. While getting synced a lot of lines like this:
`2021-03-18T20:19:35+01:00       DEBUG   Gossip  gossip/manager.go:248   error handling packet   {"err": "messageWorkerPool full: packet message discarded"}
`
## GoShimmer version

- GoShimmer version: Version v0.5.2

## Hardware specification

What hardware are you using? Docker container on Bare metal Xeon CPU host

- Operating system: Arch Linux 64bit / Linux 5.10.11-arch1-1
- RAM: 64 GB
- Number of cores: 8
- Device type: bare metal

## Steps To reproduce the bug

1.  Node fails for whatever reason, leaving db in corrupt state
2.  Remove db
3.  Start Goshimmer (debug level on) and watch logging. The message is shown very often but syncing is progressing.

## Expected behaviour

Not sure if the message is a sign that syncing process is not handling a flood of incoming messages correct.

## Actual behaviour

Buffering should be solution for a Pool that is full.

## Errors

Screenshot of the load during sync. 
![image](https://user-images.githubusercontent.com/17521100/111687864-160f3a00-882b-11eb-8dfa-38a5f496744e.png)

**Comment by jonastheis** [comment]
This issue should be fixed for a node requesting/receiving messages with https://github.com/iotaledger/goshimmer/pull/1270.
