### ISSUE TITLE
Cli-Wallet: error when sending , sends anyways, then doesn't show balance anymore.

### ISSUE THREAD

**Issue by NiC0x36** [iotaledger/goshimmer#1099]
## Bug description

I tried to send tokens with my cli-wallet over my node which hadn't any mana at the time. The transaction failed the first time with a `bad request: message could not be booked in time`, the second time also, but the transaction was carried out afterseveral minutes (due to no mana) anyways. After that, my cli-wallet showed no balances anymore despite them being correctly displeyed on the network (over my node's explorer)

Hint: before that I tried to send a transaction with more tokens than the wallet had. (check log)

## GoShimmer version

- GoShimmer: 0.5.2
- cli-wallet: 0.5.2 Windows

## Hardware specification

Node:
- Operating system: Ubuntu 20.04
- RAM: 4gb
- Number of cores: 2 vCPU
- Device type: Hetzner CX21

## Steps To reproduce the bug

_Also check log._

Preconditions:
- Use a node without any mana

Steps
1. Send more tokens than on wallet with cli-wallet:
`cli-wallet send-funds -amount 25000 -dest-addr 19n2sZ3JS5R48k8V7b59rH62wtSFpYLbaHwwHV6VtQt1u  -access-mana-id 3orCGiyGCFnDokZATSEgMuykfvc5rkbha1KEzMnQAmde -consensus-mana-id 3orCGiyGCFnDokZATSEgMuykfvc5rkbha1KEzMnQAmde`

2. Send tokens with cli-wallet:
`cli-wallet send-funds -amount 25 -dest-addr 19n2sZ3JS5R48k8V7b59rH62wtSFpYLbaHwwHV6VtQt1u  -access-mana-id 3orCGiyGCFnDokZATSEgMuykfvc5rkbha1KEzMnQAmde -consensus-mana-id 3orCGiyGCFnDokZATSEgMuykfvc5rkbha1KEzMnQAmde`

3. If it fails, check balances in cli-wallet & node explorer and repeat step 2 until you see the balances correctly in the xplorer.

4. Check if the balance gets also showed correctly in the cli-wallet

## Expected behaviour

1. Send too much tokens -> ERROR
2. Send tokens, the wallet has -> long PoW due to low mana -> OK
3. Balance shows correctly in node explorer
4. Balance shows correctly in cli-wallet

Describe what you expect to happen.

## Actual behaviour

1. Send too much tokens -> ERROR
2. Send tokens  -> ERROR  `bad request: message could not be booked in time`
3. Balances still the same
4. Try to send tokens again -> several minutes waiting -> ERROR  `bad request: message could not be booked in time`
5. Transaction anywas carried out
6. node explorer shows transaction & (apparently) correct balance
7. cli-wallet doesn't show any balance anymore.

## Errors

See cli-wallet cmd log:
[goShimmer cli-wallet log.txt](https://github.com/iotaledger/goshimmer/files/6169136/goShimmer.cli-wallet.log.txt)

Affected address according to my node's Explorer (note that the first transaction's status is rejected)
[node explorer.txt](https://github.com/iotaledger/goshimmer/files/6173946/node.explorer.txt)

**Comment by jkrvivian** [comment]
@NiC0x36 , thanks for reporting the bug!
After several attempts, this issue didn't show up in v0.7.0 on my side, so I'll close it.
But feel free to re-open it if the same happened. :smiley:
