### ISSUE TITLE
Adapt FPC integration test for mana

### ISSUE THREAD

**Issue by apenzk** [iotaledger/goshimmer#1125]
## Description

FPC integration test needs to be adapted for mana

## Motivation

Without Mana:
The non-voting entity of the faucet holds 100% of the funds. Network is split into partition A and B. Faucet distributes all funds to node a in A, and node b in B. Network is merged and all nodes have equal voting power. FPC either accepts a, accepts b, or rejects both.

With Mana:
Since after the merge a has 100% of the voting power for all nodes in A, and b 100% in B, there will be an agreement failure.

## Requirements

1. Faucet distributes proportion p of funds to node c
2. Partition the network with c being in A.
3. Faucet sends (1-p) of funds to a in A, and (1-p) of funds to b in B. 
4. Network merges and all nodes have the same perception of who holds proportion p of the mana (node c)
5. If p is large enough (90%?) FPC will finalize correctly

## Open questions (optional)

Maybe p=90% is too safe. Maybe p=50% is enough but we should check this.

**Comment by capossele** [comment]
1. Create the Transaction spending the Genesis (Txg) into 7 different outputs
2. create 6 Txs spending one output of the TXg and pledging it to each node
3. create 2 conflicting Txs (TXc1 - TXc2) both spending the remaining output from TXg

Issue to all the partitions:
TXg and TX1-6 and wait 3* NetworkAvgDelay

The rest does not change
