### ISSUE TITLE
Stuck with invalid wallet after sending 2 parallel transactions (double spends)

### ISSUE THREAD

**Issue by JanOonk** [iotaledger/goshimmer#1157]
## Bug description

If you try to send two parallel transactions using 2 cmd.exe and running `cli-wallet.exe send-funds -amount 1 -dest-addr XXX` to send funds from wallet A to B it will give an error: 
`ERROR:
  bad request: Failed to issue transaction TransactionID(BkVab1RUzvcXshTAGNViimAP4RECwUcjwMXGgk9rHce2): invalid inputs: 3EwdqaudU7N5sTto162UvuBPMBqP3xH4XrbjdYhLGMoDwNf,4BewVVerRQZbksd48baEmqpR1KRBWQWR9pdehgBsRrJzbCb,4dbFX1DmggdQWCiD77Xaq3TgBL7tojqvyaMHD5rRU7uTyBD: one or more inputs are rejected or non-monotonically liked
`

which sounds plausible, but you can't recover from this state. The wallet is and stays crashed. You can't sent any funds anymore.
Also I noticed somewhat later that my node went and stayed out of sync. Then the error became ` bad request: Failed to issue transaction TransactionID(97EZwajcfWLF76wA1bqf1VavMpchjGKEnCPSfXxmBeAR): can't issue payload: tangle not synced`

I had to restart it to get (almost instant) back in sync. Then I retried sending but then the first error was shown. So there's no way to get back to a stable functioning wallet after sending 2 parallel transactions.

## GoShimmer version

v0.5.4

## Hardware specification

Node runs in Docker on Synology NAS
cli-wallet runs on Windows 10 laptop

## Steps To reproduce the bug

1. Create two wallets (A and B)
2. Open 2 cmd.exe and go to wallet A
3. In each cmd.exe type: `cli-wallet.exe send-funds -amount 1 -dest-addr [AddressOfWalletB]` to send 1 IOTA from wallet A to B
4. Press enter fast in both cmd's to run both commands at (nearly) the same time.
5. After transactions has finished and you try to send again it will fail with error above.
 
## Expected behaviour

Wallet B should increase with 2 and Wallet A decrease with 2 and that you can still send more funds.

## Actual behaviour

Any transactions after the 2 parallel transactions will fail with error above.

## Errors

`ERROR:
  bad request: Failed to issue transaction TransactionID(BkVab1RUzvcXshTAGNViimAP4RECwUcjwMXGgk9rHce2): invalid inputs: 3EwdqaudU7N5sTto162UvuBPMBqP3xH4XrbjdYhLGMoDwNf,4BewVVerRQZbksd48baEmqpR1KRBWQWR9pdehgBsRrJzbCb,4dbFX1DmggdQWCiD77Xaq3TgBL7tojqvyaMHD5rRU7uTyBD: one or more inputs are rejected or non-monotonically liked
`

**Comment by luca-moser** [comment]
The wallet does not support parallel usage and we will prevent that in the future.
I've created issue #1520 and #1519 accordingly to track the issues you've mentioned.
