### ISSUE TITLE
FCOB AverageNetworkDelay renaiming

### ISSUE THREAD

**Issue by apenzk** [iotaledger/goshimmer#1166]
## Bug description

The parameter that is assigned to LikedThreshold and LocallyFinalizedThreshold is called FCOB.AverageNetworkDelay (and in the integration test ParaFCoBAverageNetworkDelay). However this is not the AverageNetworkDelay but a value where almost none of the messages should come in. 

Thus it should change to MaxNetworkDelay.

**Comment by jkrvivian** [comment]
Fixed and merged by #1358
