### ISSUE TITLE
[BUG] [CLI-WALLET] [config.go] Wrong JSON value for API readout

### ISSUE THREAD

**Issue by setBoolean** [iotaledger/goshimmer#1167]
## Bug description

`cli-wallet` expects the following JSON value for API access to be present in `config.json`

```
{
        "WebAPI": "http://127.0.0.1:8080",
        "basic_auth": {
          "enabled": false,
          "username": "goshimmer",
          "password": "goshimmer"
        }
}
```

But the actual structure of `config.json` is

```
"webapi": {
    "bindAddress": "127.0.0.1:8080",
    "basic_auth": {
      "enabled": false,
      "username": "goshimmer",
      "password": "goshimmer"
    }
  }
```
## GoShimmer version

Which version of GoShimmer are you running?

- GoShimmer version: 0.5.4

## Hardware specification

What hardware are you using?

- Operating system: Arch Linux (x86_64)
- RAM: 8GB
- Number of cores: 2(4)
- Device type: Laptop

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1. Run `cli-wallet` against default `config.json`

## Expected behaviour

`cli-wallet` uses the correct value from `config.json`

## Actual behaviour

`cli-wallet` fails with an error message

## Errors

```
IOTA Pollen CLI-Wallet 0.1

FATAL ERROR: json: cannot unmarshal object into Go struct field configuration.WebAPI of type string%
```

**Comment by jkrvivian** [comment]
Cli-wallet is a standalone tool having its own config.json, which is different from the one for goshimmer.

In Cli-wallet, `WebAPI` is to tell which node the wallet is going to use, it can be your own node (`127.0.0.1:8080`) or others' node. It's the same as the settings in GUI wallet. However, the `bindAddress` is the address you want to expose for web APIs of your goshimmer node.

**Comment by setBoolean** [comment]
Thanks for the clarification.
