### ISSUE TITLE
feat: Congestion Control

### ISSUE THREAD

**Issue by jkrvivian** [iotaledger/goshimmer#1186]
### High priority
1. [x] Integration tests: @acha-bill 
    - [x] Have a syncing tests with sufficient amount of messages to detect "lost messages" during switching
    - [x] Consider: Use API to check whether scheduler switched after syncing -> add to `/info` webapi
2. [x] clean up webapi `/data`, use `AwaitMessageToBeIssued` @jkrvivian 
3. [x] sync changed rethinking! currently we check the sync status every second in a loop. @Wollac 
4. [x] Fix: when the node is started synced, the FiFo Scheduler is never switched off @Wollac 
4. [x] Refactoring:
    * [x] Avoid locking event triggering section
    * [x] Code cleanup (optional)
5. [x] test with docker network
6. [x] parameter finalization
7. [x] dashboard / visualization
      * [x] rate setter rate?

### Low priority (nice to have)
1. what do we do when DiscardEvent triggers?
     a. remove msg from the storage?
    b. make sure these events are logged  @jkrvivian  `done`
2. what do we do when NodeBlackListEvent triggers?
     a. drop the node's message
    b. make sure these events are logged  @jkrvivian `done`
3. Remove the "timesamp in the future" check
4. pause the schedule-ticker when there are no messages in the inbox
5. visualize interesting metrics

### Done
1. [x] get access mana (func type) @acha-bill 
2. [x] stitch to the current data flow (Setup) @jkrvivian  
   2.1. listen to SolidEvent: fire Submit
   2.2. listen to bookedEvent: make sure parents are booked (a data structure to keep the parents book status?), call Ready
   2.3. listen to InvalidEvent: call Unsubmit
   2.4. listen to OpinionFormed: scheduled DONE.
   2.5. booker attaches to MessageScheduledEvent
4. [x] sort by timestamp (timedQ, priorityQ) @Wollac 
5. [x] tests
    5.1. test the event to see if the scheduler works as expected
    5.2. whole data flow
6. [x] bootstrapping
    6.1. a simple FIFO until sync. 
7. [x] refactor panic
      - [x]  panic if no `AccessManaRetrieveFunc`  and  `TotalAccessManaRetrieveFunc`
8. [x] Move old scheduler (FIFO) to `fifoscheduler.go`
9. [x] Wait for constructed messages to be issued by the rate setter (i.e. handle the DiscardEvent) where it makes sense, e.g. for the API
10. [x] Move the scheduler utils (e.g. buffered queue, ...) into sub package (`utils` or something)
      * Move to schedulerutils.go, due to dependency cycle 
11. [x] Add rate setter unit tests
12. [x] Have functionality to "pledge" mana dynamically to nodes (for integration tests): Use API calls
13. [x] workerpool (not async one) as queue @Wollac 
14. [x] ~after shut down, don't accept new msg, but wait until everything's scheduled~ @Wollac
15. [x] after shut down, don't accept new msg, and prune everything from scheduler; trigger `MessageDiscarded` @Wollac 
16. [x] Do not attach the unSubmit to any event
17. [x] Remove parent booked check from scheduler; consider keeping the fifo scheduler as is or used the `orderer` as well. - used the `orderer`
18. [x] events stitching:
    * [x] Attach `Ready()` to MessageSolid event
    * [x] Attach orderer to MessageScheduled event
    * [x] Attach storage deletion to MessageDiscarded event, triggered during shut down. (Currently this is done inside the scheduler, but should it rather happen inside `Storage`?)

## Note: 
1. how to deal submitted msg when shut down?
     a. after shut down, don't accept new msg, but wait until everything's scheduled @Wollac 
     b. trigger DiscardedEvent for all msgs in the queue, make sure they are persisted somewhere
2. how to deal with scheduled msg that are not booked during shut down?
     a. similar to old scheduler, a queue to ScheduledEvent?
     b. (similar to 1.a 1.b)
3. ~future ts of msg?~ -> message parser will keep future msgs in timedQ

**Comment by Wollac** [comment]
The sorting by timestamp has been added to https://github.com/iotaledger/congestion-sim but its not moved to the goshimmer branch yet

**Comment by jkrvivian** [comment]
Integrated to [v0.6.2](https://github.com/iotaledger/goshimmer/releases/tag/v0.6.2)
