### ISSUE TITLE
Refactor integration tests

### ISSUE THREAD

**Issue by capossele** [iotaledger/goshimmer#1187]
Revisit each integration test, check its logic and possibly simplify/remove tests:
- [x] autopeering @jonastheis 
- [x] common @jonastheis 
- [ ] consensus @GalRogozinski 
- [x] diagnostics @jonastheis 
- [x] drng @Wollac  
- [ ] faucet @jkrvivian 
- [x] mana @acha-bill 
- [x] message @jonastheis 
- [ ] value @jkrvivian 

## Things to check
- Replace `time.Sleep` with some sort of `assert.Eventually`
- Set reasonable timeouts instead of waiting indefinitely

**Comment by Wollac** [comment]
@daria305
PR #1478 also contains an refactoring of the `drng` tests to avoid `Sleep` and multi-threaded execution. Maybe this covers everything already.

**Comment by daria305** [comment]
@Wollac that covers all, 20 sec saved

**Comment by Wollac** [comment]
The consensus test is about to become obsolete and as such not being refactored.
Value and faucet will be refactored as part of #1478. Therefore #1478 closes this issues
