### ISSUE TITLE
Corrupted Database after Mana Panic

### ISSUE THREAD

**Issue by kaktus2** [iotaledger/goshimmer#1240]
## Bug description
My goshimmer node stops working after a panic in revoking mana from another node, then it restarts and stops again because of a corrupt database.

The error: **Revoking 1000000.000000 base mana 1 from node UqS9vgA5wjf results in negative balance**

![image](https://user-images.githubusercontent.com/2196583/116756667-c36d9400-aa0c-11eb-9063-1ebc60278cc4.png)

After the panic restart: **The database is marked as not properly shutdown/corrupted, please delete the database folder and restart.**

![image](https://user-images.githubusercontent.com/2196583/116756922-51497f00-aa0d-11eb-9b48-b69423d37c91.png)

## GoShimmer version

- GoShimmer version: 0.5.7

## Hardware specification

- Operating system: Ubuntu 20.04.2 LTS
- RAM: 16GB
- Number of cores: 4
- Device type: Intel NUC 

## Steps To reproduce the bug

After deleting the database folder it start syncing again but stops with the same error after a while.

**Comment by jonastheis** [comment]
This was fixed with the changes made in https://github.com/iotaledger/goshimmer/pull/1249. Now cMana can become negative for a brief amount of time when booking it out of order.
