### ISSUE TITLE
Static node identity: Docker yml file --autopeering.seed ignored

### ISSUE THREAD

**Issue by sdellava** [iotaledger/goshimmer#1242]
## Bug description

According the documentation, adding a  parameter to the command entry like this should keep the node identiy.

--autopeering.seed="base64:gP0uRLhwBG2yJJmnLySX4S4R5G250Z3..............="

but actually the node change identity every time is restarted.

## GoShimmer version

Version v0.5.7

## Steps To reproduce the bug

1. create a valid seed
2. add the --autopeering.seed="base64:... " to the docker-comse.yml file under the command: section

## Expected behavior

at each restart the node should keep his identity

## Actual behavior

at each restart the node renew his identity

## Errors

no error in the log. The only entry is an INFO that show the new identity and public key.

**Comment by TeeVeeEss** [comment]
@sdellava I configured in my docker-compose.yml (and in my config.json) the autopeering seed as a base58 string:
``--autopeering.seed="base58:chNbekn4Q..."``
`` "seed": "base58:chNbekn4Q... ``
That seems to work for my Goshimmer 0.5.7. node: it has always the same public key and Identity.

**Comment by sdellava** [comment]
Ok, tnx. documentation suggest to use the base64 encoding. That should be the issue.

**Comment by legacycode** [comment]
Hi, the problem still exists for base64 encoded strings. I have used the following command to generate a base58 string and this solved my problem. This issue should be fixed for base64 encoded strings.

`openssl rand 32 | base58 -`

**Comment by legacycode** [comment]
It is not a base58/base64 issue. After investigating this problem, it leads me to https://github.com/iotaledger/hive.go/issues/303
