### ISSUE TITLE
Normal output versus when redirected to stderror and stdout is different

### ISSUE THREAD

**Issue by JanOonk** [iotaledger/goshimmer#1300]
## Bug description

When you make a mistake calling the cli-wallet with wrong arguments, the output is different than when output is redirected to standard output and standard error.

## Which version of the CLI are you using?

v0.5.1

## Hardware specification

Tested on:
Windows 10 and cmd.exe (command line)
Linux

## Steps To reproduce the bug

Run for example with an incorrect dest-addr argument: 
`cli-wallet.exe send-funds -amount 1 -dest-addr 1`

Now compare above output with this redirected output:
```
cli-wallet.exe send-funds -amount 1 -dest-addr 1 > stdout.txt 2> stderror.txt
type stdout.txt
type stderror.txt
```

## Expected behaviour

Expected output when *not redirected* is the same as actual.
Expected output when *redirected*:

type stdout.txt

```
IOTA Pollen CLI-Wallet 0.1

USAGE:
  cli-wallet.exe send-funds [OPTIONS]

OPTIONS:
  -access-mana-id string
        node ID to pledge access mana to
  -amount int
        the amount of tokens that are supposed to be sent
  -color string
        color of the tokens to transfer (optional) (default "IOTA")
  -consensus-mana-id string
        node ID to pledge consensus mana to
  -dest-addr string
        destination address for the transfer
  -help
        show this help screen
```

type stderror.txt

```
ERROR:
  failed to parse Address from bytes: failed to parse Address from MarshalUtil: error parsing digest (tried to read 33 bytes from 1 bytes input): failed to parse bytes
```

## Actual behaviour

Normal output when *not redirected*:
```
IOTA Pollen CLI-Wallet 0.1

ERROR:
  failed to parse Address from bytes: failed to parse Address from MarshalUtil: error parsing digest (tried to read 33 bytes from 1 bytes input): failed to parse bytes

USAGE:
  cli-wallet.exe send-funds [OPTIONS]

OPTIONS:
  -access-mana-id string
        node ID to pledge access mana to
  -amount int
        the amount of tokens that are supposed to be sent
  -color string
        color of the tokens to transfer (optional) (default "IOTA")
  -consensus-mana-id string
        node ID to pledge consensus mana to
  -dest-addr string
        destination address for the transfer
  -help
        show this help screen

```

Output when *redirected*... notice it begins with normal output, then error and then continues with normal output:
```
IOTA Pollen CLI-Wallet 0.1

USAGE:
  cli-wallet.exe send-funds [OPTIONS]

OPTIONS:

ERROR:
  failed to parse Address from bytes: failed to parse Address from MarshalUtil: error parsing digest (tried to read 33 bytes from 1 bytes input): failed to parse bytes
  -access-mana-id string
        node ID to pledge access mana to
  -amount int
        the amount of tokens that are supposed to be sent
  -color string
        color of the tokens to transfer (optional) (default "IOTA")
  -consensus-mana-id string
        node ID to pledge consensus mana to
  -dest-addr string
        destination address for the transfer
  -help
        show this help screen
```

Just for reference here the complete list of commands and output for Windows and Linux:
Windows:
![image](https://user-images.githubusercontent.com/13236774/112284066-17a48c00-8c89-11eb-8c3f-addb340631c9.png)

Linux:
![image](https://user-images.githubusercontent.com/13236774/112283865-e2983980-8c88-11eb-8697-a7dbc1192a1a.png)

**Comment by rajivshah3** [comment]
Transferred to the GoShimmer repo as `cli-wallet` is for the Chrysalis CLI wallet

**Comment by JanOonk** [comment]
Ah ok my bad. Thanks.

**Comment by luca-moser** [comment]
We will close this issue for now and maybe revisit it later.
