### ISSUE TITLE
Dashboard does not load on Linux Precompiled package (0.6.2)

### ISSUE THREAD

**Issue by rg80** [iotaledger/goshimmer#1341]
## Bug description

Dashboard is missing some file in the precompiled official Linux package.

## GoShimmer version

Which version of GoShimmer are you running?

- GoShimmer version: 0.6.2

## Hardware specification

What hardware are you using?

- Operating system: ubuntu server 20.04 
- RAM: 3Gb
- Number of cores: 4
- Device type: Intel Nuc

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1. Download and extract linux goshimmer binary.
2. Run the goshimmer binary
3. access the dashboard via browser as usual.

## Expected behaviour

Dashboard should load.

## Actual behaviour

Browser load a blank page with the following message:

internal server error, error: open /plugins/dashboard/frontend/build/index.html: no such file or directory

## Errors

internal server error, error: open /plugins/dashboard/frontend/build/index.html: no such file or directory

**Comment by jonastheis** [comment]
This should be fixed with #1343. You just need to load the new binary from the updated release: https://github.com/iotaledger/goshimmer/releases/tag/v0.6.2
