### ISSUE TITLE
Improve Solidification and introduce multithreading

### ISSUE THREAD

**Issue by capossele** [iotaledger/goshimmer#1458]
Changing the definition of solidity of messages: The payload now also needs to be solid or respectively the message needs to weakly reference the message containing the dependable object (for example the outputs used as inputs in the child tx).

With this change we also introduce a new concurrency and locking paradigm as we finally can leverage the parallel processing that the Tangle offers implicitly.

**Comment by karimodm** [comment]
All issues related to this EPIC should be considered of low priority for now: we need to stabilize the consensus first.
