### ISSUE TITLE
Modular conflict opinion setting

### ISSUE THREAD

**Issue by capossele** [iotaledger/goshimmer#1465]
_Modular opinion setting_ is meant to simplify the dataflow and make it easy to change the way we set a node's local opinion. A nodes local opinion on a conflict is **not necessarily** the same as the objective perception according to AW. For example, with OT-FPCS it might differ from the currently perceived _heavier_ branch whereas with pure OTV it is the the same.

**Assumption:** inclusion score, only messages that are considered to be included (good timestamp, etc) are scheduled, gossiped and thus reach the TipManager

With this new modular concept we can decouple the conflict opinion setting from the dataflow. Once a message gets scheduled it is gossiped and handed to the TipManger and added to the tip pool of the corresponding branch. Only when the node wants to issue a message the opinion needs to be evaluated, because that is the time the node actually votes. To gradually implement the changes, it is reasonable to first start with a simple conflict opinion setting function such as pure OTV. Later, a metastability breaking mechanism can be introduced, simply replacing the conflict opinion setting function.

## Things to do
- [x] #1544
- [x] #1545
- [x] #1546
- [ ] Implement [OT-FPCS](https://iota.cafe/t/on-tangle-voting-with-fpcs/1218) (or other metastability breaking mechanism) as `conflict opinion setting function`

## Open questions
- How do we handle weak tips? This would require us to evaluate the opinion of the node constantly/periodically.
- There might be performance issues with lazily evaluating the local opinion on tip selection vs. updating it periodically/when booking messages

**Comment by karimodm** [comment]
Completed, with the exception of FPCS
