### ISSUE TITLE
Revamp network stack to use LibP2P

### ISSUE THREAD

**Issue by capossele** [iotaledger/goshimmer#1471]
- [ ] Replace plain TCP connections with LibP2P

**Comment by karimodm** [comment]
@georgysavva are we also using the discovery mechanism provided by libp2p (https://github.com/iotaledger/goshimmer/issues/1472) ?

**Comment by georgysavva** [comment]
@karimodm No. We kept our hive.go autopeering implementation for now. I only used libp2p for gossip connections management.
