### ISSUE TITLE
Add config keys to make bind addresses configurable

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/goshimmer#150]
* Use a single `bindAddress` key inside the configuration to configure the bind address for `gossip` and `autopeering`. The config key lives under the `network` object.
* `externalAddress`, the external IP address under which the node is reachable under the `autopeering` config object. If it is set to `auto`, we use myip.com to automatically retrieve the IP address.
* Also add a key for the webpi bind address under `webapi` config object, called `bindAddress`.
* Make also the port adjustable for the webapi.

**Comment by Wollac** [comment]
This also fixes #74
