### ISSUE TITLE
Syntactical Message validation with dislike switch

### ISSUE THREAD

**Issue by karimodm** [iotaledger/goshimmer#1570]
## Description

Upon receiving a Message, it must be syntactically validated following the changes in the message layout introduced with the dislike switch, which has been now made implicit. Refer to the [Message Structure Layout](https://github.com/iotaledger/goshimmer/blob/feat/dislike-parent-types/docOps/docs/protocol_specification/tangle.md#message-structure).
Rules:

1. A Strong Block parent must exist.
2. ParentBlock types cannot repeat.
3. Parent count per block 0 <= x <= 8.
4. Parents unique within block.
5. Parents lexicographically sorted within block.
6. ParentsBlockCount must match blocks actually parsed.
7. ParentsCount within each block must match the parents actually parsed within the block.
8. References need to be valid MessageIDs.
9. A Parent(s) repetition is only allowed when it occurs across Strong and Like parents. To support cases like this:
   
![OTV-testcases-Page-1 (2)](https://user-images.githubusercontent.com/1577639/126439358-50632eae-efce-437f-ba5c-a32e11250d7c.png)

**Comment by capossele** [comment]
Point 9. and consequently the example below does not look right. By expressing a like to B and implicitly a dislike to A, all of the children of A must be considered disliked as they depend on A.

**Comment by karimodm** [comment]
Yep, you are very right. Fixed the image ;)

**Comment by GalRogozinski** [comment]
I thought that point (8) means to check the PoW difficulty
But the messageID is different that the PoW hash (BLAKE-256 vs BLAKE-512)... so I am not sure what should be validated there...

**Comment by GalRogozinski** [comment]
Point 8 has been removed..

Another check was added to ensure blocks are ordered by their types in ascending order

**Comment by jonastheis** [comment]
Merged with #1577
