### ISSUE TITLE
Remove legacy state flags

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/goshimmer#1603]
Branch (JSON):
- [x] Remove liked, monotonicallyLiked, inclustionState, finalized

MessageMetadata (explorer, JSON, diagnostic):
- [x] Remove finalized, finalizedTime, eligibile

TransactionMetadata:
- [x] Remove finalized

OutputMetadata:
- [x] Remove finalized
- [x] Check first/confirmed consumer needed

**Comment by jonastheis** [comment]
Open tasks:
- [ ] fix integration tests
- [ ] fix cli wallet (pending & confirmed balances)
- [ ] dashboard: adjust explorer and visualizer
