### ISSUE TITLE
Marker Simplification

### ISSUE THREAD

**Issue by jonastheis** [iotaledger/goshimmer#1623]
Due to the changes of #1539 and #1486 tracking of AW for markers is now independent of branches. As such, markers for AW can be simplified to just use one sequence across the whole tangle to approximate weight on messages.  

Since we still use markers as a performance optimization to map chunks of the tangle to a branch, we need to introduce two separate marker tools with different inheritance rules:
1. Single sequence to approximate AW for messages
2. Branch mapping via markers (currently implemented and therefore nothing to do, except maybe renaming)

**Comment by karimodm** [comment]
Opmitization issues take lower priority.

**Comment by jonastheis** [comment]
Markers were simplified with #1460.
