### ISSUE TITLE
Implement generic serialization

### ISSUE THREAD

**Issue by piotrm50** [iotaledger/goshimmer#1629]
Implement generic serialization/deserialization package using reflection, so that it’s not necessary to explicitly implement this for every structure that we want to have serialized. This eases on the one hand development as currently there is some overhead for writing the same stuff manually. On the other hand, it’s less prone to errors since serialization/deserialization is done programatically instead of explicitly coded.

* Maybe using generics as for #2002 

Involve @luca-moser, @muXxer and @alexsporn , as they will be affected by these changes.

**Comment by karimodm** [comment]
It would be awesome to have this when we add a new model. For now not really a blocker for any outstanding priority though.
