### ISSUE TITLE
DAGs visualizer

### ISSUE THREAD

**Issue by apenzk** [iotaledger/goshimmer#1648]
draft visualizer tools, organise with Begona.

The DAGs visualizer will be a new Goshimmer plugin. The benefit is that we can easily add and modify APIs or events to the node to get data if needed. We decided to build the visualizer with **React**, in case we want to embed or combine this plugin to the dashboard or official website.

The diagrams below show the possible layout of the DAGs visualizer:
* Get data of selected/hovered vertex:
![image](https://user-images.githubusercontent.com/11289354/131297925-b06b9281-188c-4619-8381-f6de8e1b7475.png)
* Align a selected vertex in different DAGs
![image](https://user-images.githubusercontent.com/11289354/131298529-3a76fc8e-fbab-4f01-9b67-8a972c8c8c50.png)
* Each window is collapsable
![image](https://user-images.githubusercontent.com/11289354/131298994-307c7c92-d4b0-4dc9-ba0b-a6b1007b68fc.png)

### phase 0 - libraries
1. Design and implement libraries to handle data from different DAGS

### phase 1 - visualization
1. Find a suitable visualization library
2. Visualize vertices of the three DAGs
3. Vertex amount per DAG
4. Show msg/tx/branch within the given time interval
5. Pause rendering
6. Hover / click to show infos
7. Collapsable windows

### phase 2 - DAGs relation
1. Synchronization button
    A toggle button that turns synchronizing of the DAGs on and off. If ON then clicking on a vertex in one DAG moves the respective vertex onto the same x-location also in the other DAGs.

### phase 3 - DAGs tweaks
1. Vertex search per DAG
2. Optimize visualization details per DAG
    * Tangle
        * Show the different types of parents
        * Marker layer (mark markers with different color)
    * UTXO
        * Visualize input / output
        * visualize conflict sets
    * Branch
        * (togglable) Block size reflected the given approval weight (the bigger the heavier)

### phase 4 - Add more stuff
1. Add more DAGs
2. Other functionalities

**Comment by karimodm** [comment]
Master of Graphs: @apenzk
