### ISSUE TITLE
Remove MongoDB 

### ISSUE THREAD

**Issue by piotrm50** [iotaledger/goshimmer#1660]
MongoDB is only used to collect data about FPC conflicts. For new consensus mechanism it will not be needed and can be entirely removed from the code, docker-compose and existing deployments. 

TODO:

- [x] remove mongoDB from local docker network scripts
- [x] remove `peer-entry.sh` and `wait-for.sh` scripts in docker network [here](https://github.com/iotaledger/goshimmer/blob/develop/tools/docker-network/builder) and update docker network's `docker-compose.yaml` accordingly.
- [x] remove mongoDB from predevnet deployment [here](https://github.com/iotaledger/goshimmer/tree/dev/consensus/deploy/ansible)
- [x] remove mongodb from the devnet deployment and internal testnet running on `ressims.iota.cafe` - I think this needs to be done after the release of the new consensus mechanism.

**Comment by jonastheis** [comment]
1 and 2 out of the list above have been already addressed with https://github.com/iotaledger/goshimmer/pull/1657 due to incompatibility with the `distroless` image.

**Comment by piotrm50** [comment]
Addressed the third point from the list with https://github.com/iotaledger/goshimmer/pull/1703
The last one should be resolved after the release of the new consensus.
