### ISSUE TITLE
Goshimmer node stucks synching

### ISSUE THREAD

**Issue by dahof1** [iotaledger/goshimmer#1688]
## Bug description

Starting a goshimmer node with docker. After 3/4 hours the synchronizing stucks on Timespamp: `Time: 16.08.2021 23:41:11` and it doesn't go further. Currently the node is up for more than 12 hours. Neighbors currently 8.

(Sidenote: I also compiled it before by myself and also there i experienced this behavior. The node was up for more than 2 days and the syncing stucks at the above time)

## GoShimmer version

- GoShimmer version: 0.7.5

## Hardware specification

What hardware are you using?

- Operating system: Ubuntu 20.04 (2021-06-01) 
- RAM: 16
- Number of cores: 4
- Device type: VPS

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1. Following this steps: https://goshimmer.docs.iota.org/docs/tutorials/setup/#why-you-should-run-a-node
2. `docker-compose -d up`
3. After 3/4 hours the syncing makes no progress anymore

## Expected behaviour

Syncing should successfully finish.

## Actual behaviour

Syncing stucks at the above timestamp

## Errors

![grafik](https://user-images.githubusercontent.com/46201601/133388347-2ce5f671-6d32-4ca7-bab4-ce2b55af7441.png)

**Comment by turnikuta** [comment]
I observe the exact same problem ...
![Screenshot_2021-09-16_21-22-04](https://user-images.githubusercontent.com/47212210/133672811-5f1977e1-fde4-4cae-b3e0-8c266a383909.png)

**Comment by alorraine** [comment]
The same unfortunately. Several attempts made.

**Comment by turnikuta** [comment]
In version 0.7.6 the described problem does not appear anymore...

**Comment by dahof1** [comment]
Installed 0.7.6. Problem gone :)
