### ISSUE TITLE
Structured Testing

### ISSUE THREAD

**Issue by jonastheis** [iotaledger/goshimmer#1728]
Use the old test tool with added ledger verification functionality to stress test the node and new consensus implementation in various ways.

- double spends
- multiple (e.g. hundred) spends
- spends in child branches (deep branch DAG)
  - reject and approved branches

**Comment by daria305** [comment]
Scripts for spamming tests are updated for GoF changes. For now tests were done only in a docker network:
there was no problems with data/transaction spaming. But something bad is going on when we spam double spends for a longer period of time. 

**Test 1:**
start spam with 10mps for 10s, then increased by 10 mps and repeated up to 50mps.

There start to show up errors like this for all nodes:
```
peer_replica_2  | 2021-10-06T14:07:20Z  ERROR   MessageLayer    node/plugin.go:74       error in Booker: failed to book message with MessageID(TBJV1ghxAmJtAAdv129Bzioj6Gj8EVqcA2Y5BmajXHT): failed to inherit Branch when booking Message with MessageID(TBJV1ghxAmJtAAdv129Bzioj6Gj8EVqcA2Y5BmajXHT): failed to normalize Branches: combined Branches are conflicting: invalid state transition
```
Network is still synced, but it is no longer possible to spam with normal valid transactions, at least a lot of them is pending, and sometimes there shows an error:
``` 
2021-10-06T14:16:04Z  ERROR   MessageLayer    node/plugin.go:74       error in MessageFactory: pow failed: a block must have at least 1-8 parents
```

**Test 2 (higher rate):**
start spam with 50mps for 10s, then increased by 5 mps and repeated up to 100mps.

Conflict resolution times increased up to 1, 2, or even 3 minutes, before one of the spamming nodes went out of sync. It was about 2700 double-spent issued. A moment after all network was out of sync.

```
2021-10-06T16:38:46+02:00       INFO    Script  scripts/double-spend-test.go:36 already sent about 2700 double spends, waiting 5sec before next test

2021-10-06T16:39:06+02:00       INFO    Script  scripts/double-spend-test.go:39 Sync status: [true false]
```
Scripts used for tests are here: https://github.com/iotaledger/goshimmer-tools/blob/update-std-test-consensus/internal-tools/standardized-tests/main.go

Just update URLs list in `main.go` and use `DoubleSpendTest` to test only double spends
