### ISSUE TITLE
Rename autopeering.seed to autopeering.idseed

### ISSUE THREAD

**Issue by c-mnd** [iotaledger/goshimmer#173]
to make it clear (more obvious), that it's not an IOTA-seed (searchability as well).
For consistency reasons, also change CFG_SEED to CFG_IDSEED.

(Not an issue, I'm just wonnderig ...)
Is this useful feature intentionally not yet in the README.md?
What happens if I use the same idseed on two machines simultaneously?

**Comment by luca-moser** [comment]
We are not going to change it.
