### ISSUE TITLE
Dashboard does not work on mobile browsers anymore

### ISSUE THREAD

**Issue by JannemanDev** [iotaledger/goshimmer#1748]
## Bug description

http://[nodeip]:8081/dashboard does not work anymore in **_mobile_** browsers, tried in FireFox, Safari, Chrome and DuckDuckGo using an IPhoneX with latest iOS v15.0.2
It shows the Dashboard website but some labels are not filled with values and graphs are not loading.

The http://[nodeip]:8080/info does work and shows all the current stats.
Also both webpages/urls work on Desktop using all major browsers.
Also it did work on older versions... I think <=v0.7.5

## GoShimmer version

- GoShimmer version: v0.7.7
![IMG_3277](https://user-images.githubusercontent.com/13236774/136958348-9b7dc26c-a984-45b6-b435-f705b741b3f9.PNG)

**Comment by jkrvivian** [comment]
The dashboard works on mobile with v0.9.8.
