### ISSUE TITLE
Fix GoReleaser step in release workflow not working

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/goshimmer#1755]
During the v0.7.7 release, the GoReleaser step was unable to successfully upload the .tar.gz file containing the goshimmer binary and other assets: https://github.com/iotaledger/goshimmer/runs/3845869592?check_suite_focus=true

**Comment by georgysavva** [comment]
The error looks like a temporary issue, most likely some Github services were down at the time of upload and it broke GoReleaser logic/state. 
I just tried to run this GoReleaser action (without actually deploying anything) and it works as expected:
https://github.com/iotaledger/goshimmer/runs/4082455342?check_suite_focus=true
So I think there is nothing to fix on our side and we are good to use it for the next Release:
@jonastheis @karimodm

**Comment by jonastheis** [comment]
Ok thanks for checking this @georgysavva! We'll try with the next release. Closing this issue.
