### ISSUE TITLE
Out of Memory during Sync

### ISSUE THREAD

**Issue by AdrianMarks** [iotaledger/goshimmer#1771]
## Bug description

Unable to complete the synchronisation process due to out of memory failure when rebuilding from a snapshot that is now quite old.

## GoShimmer version

- GoShimmer version: 0.7.7

## Hardware specification

- Operating system: Ubuntu 20.04.03
- RAM: 4GB
- Number of cores: 2
- Device type: Hetzner CX21

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

Follow the standard Wiki Install process and attempt to resync from the available latest snapshot.bin. 

## Expected behaviour

Synchronisation to complete successfully.

## Actual behaviour

Synchronisation begins successfully but after many hours (6+) Console message suggests Goshimmer has been terminated due to Out of Memory.

## Errors

No errors visible in the log file. 

Console Message:
[Console Message.pdf](https://github.com/iotaledger/goshimmer/files/7448575/Console.Message.pdf)

**Comment by jonastheis** [comment]
Closing this for now, as we're already many versions progressed and the issue might be naturally resolved. If not the issue can be reopened.
