### ISSUE TITLE
Create Action workflow to deploy `Feature` network

### ISSUE THREAD

**Issue by jonastheis** [iotaledger/goshimmer#1774]
GitHub Actions pipeline to trigger the deployment of the network, allowing to deploy any arbitrary branch of revision of the codebase.
The pipeline should receive as arguments:

1. Revision to deploy
2. PoW difficulty for the network (let's make it same for Faucet and Message PoW)
3. Custom snapshot URL to download

**Comment by piotrm50** [comment]
Only people who have write access to the repository will be able to run the workflow manually when they need to deploy their branch to the Feature network. 
The pipeline will use the Feature environment with all the secrets and all branches in the GoShimmer repository will be allowed access to this environment's secrets. 
PRs created from forked repositories will not be able to access the secrets as they are not part of the GoShimmer repository.
