### ISSUE TITLE
Feature Network

### ISSUE THREAD

**Issue by karimodm** [iotaledger/goshimmer#1788]
This EPIC contains all those issue regarding the _Feature_ network.
The _Feature_ is a special internal network purely used for debugging and understanding stuff.

* The network already lives in a Hetzner Cloud organization as multiple VMs, same setup as pre-devnet.
Machines:
```
metrics-01.feature.shimmer.iota.cafe
analysisentry-01.feature.shimmer.iota.cafe
bootstrap-01.feature.shimmer.iota.cafe
vanilla-01.feature.shimmer.iota.cafe
drng-01.feature.shimmer.iota.cafe
drng-02.feature.shimmer.iota.cafe
drng-03.feature.shimmer.iota.cafe
drng-04.feature.shimmer.iota.cafe
drng-05.feature.shimmer.iota.cafe
faucet-01.feature.shimmer.iota.cafe
drand-01.feature.shimmer.iota.cafe
```
* The Action should be triggered only manually, not upon PR or push. Only people having write access to the repo are allowed to run the Action: the number of users having _write_ access to this repo has been **greatly** reduced.
* The secrets will stay in a separate environment; only accessible to branches of this same repo, _not_ to forks.
* Custom snapshot support: even if we don't have a tool yet to create them we should allow upload / download of an arbitrary snapshot.
* A mechanism should be put in place to allow remote debugging on any machine forming the network.

**Comment by georgysavva** [comment]
@karimodm does it make sense to start using docker swarm/k8s for this type of network? 
we would also need a Github action to undeploy the feature network when PR is closed/merged.

**Comment by karimodm** [comment]
It would definitely nice, but I think the network won't have so much usage to justify a K8S cluster! For now I've created a infrastructure "clone" of pre-devnet; just the same system with different secrets.
