### ISSUE TITLE
Feature network: allow remote debugging

### ISSUE THREAD

**Issue by karimodm** [iotaledger/goshimmer#1814]
Remote Delve debugging should be possible on any specific host comprising the network. `dlv attach` on the desired host and exposing a port to connect your IDE to.
**The connection must be authenticated!**

**Comment by karimodm** [comment]
This could be done in two main ways:
1. Deploy delve as part of the Ansible deployment: the debugger is always attached on every machine, and always bound to a port.
2. To have a "Debug" pipeline that will use the feature environment and that will receive a machine name as a parameter and will use Ansible to deploy Delve, Attach and expose.

**Comment by georgysavva** [comment]
@karimodm I decided to go with the first approach. Delve binary will be included in the result Goshimer Docker image. Delve will "wrap" the Goshimmer process and expose the debugging port. It will only affect Docker images we build for the feature network.

Regarding the authentication, it seems that Delve doesn't have such feature built-in, see:
https://github.com/go-delve/delve/issues/2669
https://github.com/go-delve/delve/issues/861
They suggest authenticating via SSH. Or perhaps we could put it behind Traefik/LB?

**Comment by karimodm** [comment]
@georgysavva There is no need to include the Delve binary within the Docker image! You can attach to the process from the host namespace; this should prevent a few extra steps. I believe SSH connection is the only viable option; as IDEs probably do not support HTTP-based authentications.

**Comment by georgysavva** [comment]
@karimodm yes we could do as you say, but I thought that optionally having a delve binary inside the Goshimmer image is helpful regardless of the Feature Network environment. Someone might that to debug their Goshimmer locally inside docker or docker-network.
