### ISSUE TITLE
Tangle DAG: Use different line styles according to different parent types

### ISSUE THREAD

**Issue by jkrvivian** [iotaledger/goshimmer#1834]
There are different types of parents of a message, it would be nice to show the difference in the Tangle DAG.

Types of parent:
* [x] strong parent, solid
* [x] weak parent
* [x] liked parent

**Comment by daria305** [comment]
Update: Tangle graph is generated with `vivagraphjs` library and it uses webgl based graph rendering. The default implementation does not allow to change any other link attribute than color. Two possible solutions will be considered:
 - stay with webgl and create custom linkProgram that allows for creation of more customizable links
 - change webgl to svg graphics, that allows to easily customize the links. With this approach need to change if the performance is not dropping when many messages are drow.
