### ISSUE TITLE
Discard buffered messages on shutdown

### ISSUE THREAD

**Issue by piotrm50** [iotaledger/goshimmer#1839]
Currently during shutdown the node waits until all the messages from the scheduler are scheduled and only after that the node can shutdown correctly.
This is no longer necessary and the messages from the queue should be discarded on shutdown without waiting for them to be scheduled or persisted.

**Comment by piotrm50** [comment]
Also, on confirmation remove messages (call `Unsubmit`) that are not yet ready from the Scheduler. 
For messages that are marked as ready, they need to be skipped in the Scheduler. So when when Scheduler selects a message that is already confirmed, it should take the next one.

**Comment by capossele** [comment]
That is done in #1794
