### ISSUE TITLE
Visualize/analyze new metrics in Kibana

### ISSUE THREAD

**Issue by piotrm50** [iotaledger/goshimmer#1887]
After adding metrics to Elasticsearch, use Kibana (or Python scripts) to create some plots and queries that aggregate raw data and give useful insights.

List of metrics:
https://docs.google.com/document/d/1BVNgRtSGbBrKeGwFgj_lbyN1PoTr_Ddd2GZ7l6J0nO8/edit#

**Comment by GalRogozinski** [comment]
### Fundamental Stats:

[ ] Arrival time t_A(m,n)
[ ] Solid/booked time t_B(m,n)
[ ] Enqueuing time t_E(m,n)
[ ] Dropped time t_D(m,n)
[ ] Scheduled time t_S(m,n)
[ ] Time at which message m is scheduled by node n
[ ] Confirmed time t_C(m,n)

### Buffer
[ ] Queue length q(n,t) 
[ ] Mana-scaled queue length q(n,t)/mana(n)
[ ] Total buffer size B(t)=iNq(n,t)

### Derived metrics
[ ] Message m scheduled by everyone
[ ]Message m booked by everyone
[ ]Message m confirmed by everyone
#### Dissemination delays

[ ] Scheduled delay T_S(m)-T_I(m)
[ ] Booked delay T_B(m)-T_I(m)
[ ] Confirmed delay T_C(m)-T_I(m)

**Comment by GalRogozinski** [comment]
This PR is where one can find the kibana metrics:
https://github.com/iotaledger/goshimmer-tools/pull/44

**Comment by JanOonk** [comment]
better to make the document private or readonly for public
