### ISSUE TITLE
Abstract transaction related APIs, spammers and implement evil wallet

### ISSUE THREAD

**Issue by jkrvivian** [iotaledger/goshimmer#2022]
Evil wallet lib should provide easy-to-use facilities to do, along others:

* [x] Move spammer tools to GoShimmer (as a library with building blocks, no ready tools)
* [x] refactor spammer tools
* [x] evil wallet design spamming
* [x] Wrap up transaction-related APIs
  * [x] wait for message confirmation
  * [x] issue a double-spend without dealing with keys and outputs
  * [x] issue simple double-spend
  * [x] issue nested double-spend: double-spend a double-spent output
* [x] Make output handling automated - a user does not need to specifically provide output.

**Comment by karimodm** [comment]
Also refer to https://github.com/iotaledger/goshimmer-tools/issues/38

**Comment by daria305** [comment]
Also related PR: #2124
With that all basic functionality supporting deep spam and faucet requesting is done and issue can be closed
