### ISSUE TITLE
Improve conflicts dashboard page

### ISSUE THREAD

**Issue by jonastheis** [iotaledger/goshimmer#2039]
The conflicts page on the dashboard has some odd behaviour on different nodes. 

The dashboard should always
- show conflicts sorted by time 
- show the latest 50 (?) conflicts independently whether the dashboard was open, the node was online or just recently synced up

Overall, the conflicts page should give an accurate picture of conflicts in the system and thus be comparable between nodes.

**Comment by jkrvivian** [comment]
Already implemented.
