### ISSUE TITLE
Refactor evil wallet, spammer, tool

### ISSUE THREAD

**Issue by jkrvivian** [iotaledger/goshimmer#2126]
* [x] Remove testing files in evilwallet

**Comment by pqmertz** [comment]
Can be done with two nodes, cli-wallet and copied wallet.dat file from one to the other.   request-funds setup a cron job to send a token every minute.   Bam conflicts and pending funds.

**Comment by daria305** [comment]
Clever, but we're building the tooling that will also allows for creation of deep structures in branch and UTXO DAG. See  screenshots from: #2145
