### ISSUE TITLE
Badger: Constant overflows int problem

### ISSUE THREAD

**Issue by sks-90** [iotaledger/goshimmer#224]
**Describe the bug**
Getting following badger error message after build:
`.../value.go: 859:38: constant 4294967295 overflows int`

**To Reproduce**
- `git clone https://github.com/iotaledger/goshimmer.git`
- Go to `goshimmer` directory
- `go build -o goshimmer`
- See error

**Expected behavior**
Installing all dependencies and build executable file.

**Environment information:**
 - OS: Raspbian Buster Lite
 - RAM: 4 GB
 - Cores: 4 Cores
 - Type: Raspberry Pi 4
 - GoShimmer version 1.13.6

**Additional context**
![2020-02-03_GoShimmer_Issue_01](https://user-images.githubusercontent.com/4050536/73686623-a1317d00-46c8-11ea-9931-78b180c99eb4.jpg)
![2020-02-03_GoShimmer_Issue_02](https://user-images.githubusercontent.com/4050536/73686835-0ab18b80-46c9-11ea-835c-dcf058208c4e.jpg)

After manual installation of badger and go build, getting this error:

1. `export GO111MODULE=on`
2. `go get -u github.com/dgraph-io/badger/v2@master`
3. `go build -o goshimmer`

![2020-02-03_GoShimmer_Issue_03](https://user-images.githubusercontent.com/4050536/73686972-55330800-46c9-11ea-9ecb-b5bc5f4579a7.jpg)

**Comment by ioiobzit** [comment]
Same here with dietpi

![image](https://user-images.githubusercontent.com/7383572/73766399-3e96ba80-4776-11ea-8c62-e4bc3e3ce325.png)

**Comment by l3wi** [comment]
Same here with RPi 0 W

**Comment by luca-moser** [comment]
This is blocked through https://github.com/dgraph-io/badger/issues/1182
