### ISSUE TITLE
Dashboard stops showing stats after some hours uptime

### ISSUE THREAD

**Issue by svenger87** [iotaledger/goshimmer#227]
**Description**

The Dashboard stops showing the graphs and stats after some hours. The log doesn´t give any useful information as far as i can see.

EDIT: Switched log to debug and check if there is some more information when the dashboard stops giving information.

**Environment information:**
 - OS: Ubuntu 18.04
 - RAM: 4 GB
 - Cores: 2 Cores
 - Type: VPS Hetzner CX21
 - GoShimmer version 0.1.0 compiled from master branch

![image](https://user-images.githubusercontent.com/35897839/73718820-d5835880-471d-11ea-8d6d-c241ec1249b6.png)

**Comment by MaKla89** [comment]
Can confirm, same issue over here. Log seems okay (synced and updating, providing new messages as expected), Dashboard did work yesterday evening, does not any more since this morning.

**Environment:**

- Contabo VPS
- Ubuntu 18.04.4 LTS
- 6 cores
- 16 GB RAM
- GoShimmer installed according to GitHub manual (NOT playbook)

**Comment by luca-moser** [comment]
Just to confirm, you guys are actually refreshing the page, right?

**Comment by centercirclesolutions** [comment]
I can confirm that for me I refreshed and the charts still were empty

**Comment by MaKla89** [comment]
> Just to confirm, you guys are actually refreshing the page, right?

This morning I even used a completely different PC to check on the dashboard AND tried F5  +  Ctrl-F5 to no success :)

**Comment by luca-moser** [comment]
thanks. does anybody perhaps have a log where one can see a stracktrace of some sorts regarding the SPA?

**Comment by svenger87** [comment]
> thanks. does anybody perhaps have a log where one can see a stracktrace of some sorts regarding the SPA?

Will try to get some logs. Hope the loglevel debug gives some information.

**Comment by MaKla89** [comment]
Just skimmed through goshimmer.log (with default log-level) and could not find anything about "SPA". Should I attach the lofgile or is this a bad idea due to all the IP-addresses of my neighbors?

**Comment by centercirclesolutions** [comment]
[dashboard_empty.log](https://github.com/iotaledger/goshimmer/files/4152319/dashboard_empty.log)
Here's a log from my node when dashboard was empty. I've probably gone back too far but I was not sure how long it had been empty (not more than 15 min). Also I noticed about several minutes of higher TPS (100 or so) when the dashboard froze. Then after the I refreshed the browser it did not show any stats.

**Comment by svenger87** [comment]
Can´t get any logs for the dashboard issue with Loglevel debug either.

**Comment by wonkytonky2** [comment]
confirm same issue win 10

**Comment by centercirclesolutions** [comment]
I can confirm this issues still exists on Develop branch. What I have observed as a consistent situation is that Goshimmer runs for some time then has an increase in transactions (usually large) during this increase the dashboard freezes and when refreshed contains the charts but stops refreshing or showing any history (blank charts). In the log it looks like the gossip plugin.go log messages ( connection established / neighbor removed) cease.

![image](https://user-images.githubusercontent.com/44786846/73798890-16548f00-4769-11ea-90c9-36ef1a9f252d.png)

**Comment by luca-moser** [comment]
Can someone upload a full goroutine stacktrace? Every GoShimmer node has per default `pprof` enabled, where you can find debug information about the node. You should be able to grab it via http://127.0.0.1:6060/debug/pprof/goroutine?debug=2 (of course, you'd have to use curl or something when doing it on a VPS).
I'm sure that something deadlocks somewhere, leading to no WebSocket message getting sent downstream anymore.

**Comment by luca-moser** [comment]
Never mind, I was lucky enough to get the deadlock fast enough:
```
goroutine 67 [semacquire, 5 minutes]:
sync.runtime_SemacquireMutex(0xc00011ca50, 0xc00, 0x0)
	/snap/go/5243/src/runtime/sema.go:71 +0x47
sync.(*RWMutex).RLock(...)
	/snap/go/5243/src/sync/rwmutex.go:50
github.com/iotaledger/goshimmer/packages/gossip.(*Manager).GetAllNeighbors(0xc00011ca20, 0xc0006bbdc0, 0x7f91440d83e0, 0x26)
	/opt/goshimmer/build/packages/gossip/manager.go:141 +0x228
github.com/iotaledger/goshimmer/plugins/gossip.GetAllNeighbors(...)
	/opt/goshimmer/build/plugins/gossip/gossip.go:132
github.com/iotaledger/goshimmer/plugins/spa.neighborMetrics(0xc02480, 0xc0211a84c0, 0xc000596088)
	/opt/goshimmer/build/plugins/spa/plugin.go:172 +0x3f2
github.com/iotaledger/goshimmer/plugins/spa.configure.func1(0xc034bc2dc0, 0x1, 0x1, 0xc03d51d800)
	/opt/goshimmer/build/plugins/spa/plugin.go:49 +0x117
github.com/iotaledger/hive.go/workerpool.(*WorkerPool).startWorkers.func1(0xc0004501e0)
	/root/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200121213505-28904d5f037c/workerpool/workerpool.go:159 +0x1ad
created by github.com/iotaledger/hive.go/workerpool.(*WorkerPool).startWorkers
	/root/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200121213505-28904d5f037c/workerpool/workerpool.go:135 +0x5e
```
