### ISSUE TITLE
Goshimmer node discovers neighbors but doesn't sync

### ISSUE THREAD

**Issue by davigldom** [iotaledger/goshimmer#2357]
## Bug description
I started a Goshimmer node with the Docker image following this steps: https://wiki.iota.org/goshimmer/tutorials/setup. After 30 minutes, number of neighbors is 8 but node doesn't sync with the Tangle (see images below).

## GoShimmer version
- GoShimmer version: 0.9.3

## Hardware specification
- Operating system: Debian 10.12 (Buster)
- RAM: 2 GB
- Number of cores: 2
- Device type: Virtual Machine

## Steps To reproduce the bug
1. Following this steps: https://wiki.iota.org/goshimmer/tutorials/setup
2. `docker-compose -d up`
3. After 30 minutes, the node doesn't sync with the Tangle

## Expected behaviour
Syncing should successfully finish.

## Actual behaviour
"TangleTime Synced: No"

## Errors
![1](https://user-images.githubusercontent.com/34518143/180428431-aa6054be-5bbc-463c-83b8-8446256f0562.png)
![2](https://user-images.githubusercontent.com/34518143/180428450-526a8bf0-7a79-4527-addd-df86ae2f9016.png)

**Comment by JannemanDev** [comment]
For the first time syncing after a few days takes alot of time. Just yesterday someone in Discord had to wait 4 hours.
I have just started a new node a few hours back and it is still syncing after 3 hours and 40 minutes.
I calculated that currently it takes 2 min of realtime to sync 1 hour and 30 min of data. My node will probably be synced after almost 5 hours. So just have more patience :) until we have working snapshots and pruning(?).
![image](https://user-images.githubusercontent.com/13236774/180432974-d7172dfa-e476-4860-b208-7511565652fc.png)

**Comment by davigldom** [comment]
Yeah, but the problem was that the node didn't start to sync (see that my "Last Accepted Block" was "1111...."). Now, I added to my docker-compose.yml the environment variable "TZ=europe/london" and the node started to sync, so I think that my "/etc/timezone" file wasn't working properly.

Before(without TZ environment variable):
![1](https://user-images.githubusercontent.com/34518143/180434134-855d7f18-7234-4d3a-ac28-3ac50e99c0a3.png)

Now (with TZ):
![3](https://user-images.githubusercontent.com/34518143/180434342-ce928903-5c65-4372-ba40-57aca5968d6a.png)

**Comment by davigldom** [comment]
Just have to wait 5 hours to sync, so it didn't have a problem.
