### ISSUE TITLE
9 Neighbors allowed

### ISSUE THREAD

**Issue by centercirclesolutions** [iotaledger/goshimmer#243]
# Issue
After running for 24 hours Node shows 9 neighbors

# Environment
Hertzner CX41 Ubuntu 18.04 Goshimmer 1.1

[Stack Dump](https://github.com/iotaledger/goshimmer/files/4174938/goroutine.zip)
![9 Neighbors](https://user-images.githubusercontent.com/44786846/74090471-90825d80-4a60-11ea-97e5-de925d23a5a8.png)

**Comment by centercirclesolutions** [comment]
I believe the previous stack dump was from the Hornet node process. Here is the log from goshimmer. The errors are repeated until the end of the log

![image](https://user-images.githubusercontent.com/44786846/74090826-e527d780-4a64-11ea-86ca-f792beab1806.png)

**Comment by Wollac** [comment]
Fixed in the net release https://github.com/iotaledger/goshimmer/pull/347#pullrequestreview-398117970
