### ISSUE TITLE
Create new dashboard for epoch metrics

### ISSUE THREAD

**Issue by jonastheis** [iotaledger/goshimmer#2542]
Add the following metrics to GoShimmer and create dashboard to display them:
- Conflicts (epoch scaled)
  - seen conflicts -> do it the same way as in notarization manager
  - accepted conflicts
  - rejected conflicts
  - decided conflicts

- Blocks (does not really relate to epoch commitments)
  - seen blocks
  - orphaned blocks
    - orphaned transactions
    - orphaned conflicts

**Comment by piotrm50** [comment]
PRs need to be merged (one with metrics and one with in-memory conflict DAG contain those changes)
