### ISSUE TITLE
Command Line parameters -d and -c do not work

### ISSUE THREAD

**Issue by centercirclesolutions** [iotaledger/goshimmer#258]
Changing the directory and / or name for the default config file do not work. Viper always uses the default '.' directory

**Comment by centercirclesolutions** [comment]
I was able to make it work by modifying paramater.go adding the command line flags outside of the hive.go LoadConfigFile function. I"m not sure if this is the right solutions as it might overwrite command line options with the config file.
![image](https://user-images.githubusercontent.com/44786846/74609414-9bf80900-509e-11ea-9cc7-b3d2d8af1c18.png)

**Comment by capossele** [comment]
Fixed by b526983481506c7e971356e28f160b59d090617b
