### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by luca-marchiori** [iotaledger/goshimmer#261]
**Describe the bug**
goshimmer starts normally, but crashes after a few minutes with msg:

`panic:` runtime error: slice bounds out of range [:7581] with capacity 1160'

**To Reproduce**
- start goshimmer
- wait a few minutes
- WebUI disconnects, the error above is logged

**Environment information:**
 - OS: Ubuntu 18.04.4 LTS]
 - RAM: [4 GB]
 - Cores: [2 Cores]
 - Type: [ESXi VM]
 - GoShimmer version [e.g. 0.1.1]

**Additional context**
GoShimmer log attached

**Attempted:**
deleting `mainnetdb` folder and restarted - no change 

[goshimmer panic.txt](https://github.com/iotaledger/goshimmer/files/4228437/goshimmer.panic.txt)

**Comment by jonastheis** [comment]
This is going to be fixed with #262.
