### ISSUE TITLE
Update the OAS file to reflect changes to the web API

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/goshimmer#268]

**Comment by jkrvivian** [comment]
Web APIs:

| Category | Method | Route | Usage |
| ------ | ---- | ---- | ----- |
|  Node  | GET | `autopeering/neighbors`  | Retrieve neighbor info |
|  Node   |  GET  |  `info/`  | Get node info |
|  DRNG | GET | `drng/info/committee`  | Retrieve committee info |
|  DRNG | GET| `drng/info/randomness`  |  Get DRNG randomness |
|  DRNG  | POST | `drng/collectiveBeacon` |  Send collective beacon |
|  Spam   |  GET |  `spammer/`  |  Start/stop spammer  |
|  Message  | GET | `getMessageByHash/`  | Find msg by Id |
|  Message  | GET | `message/findById` | Find msg by Id |
|  Message  | POST | `data/` | Broadcast data msg |
|  Faucet   | POST | `faucet/` | Send faucet request to request funds |
| :construction: Value  | GET | `value/balance` | Get balance |
| :construction: Value  | POST | `value/sendToken` | Send token |

**Comment by luca-moser** [comment]
We can either use code annotation to automatically generate the appropriate OAS file or just get rid of the file all together.
