### ISSUE TITLE
No error/warn reported if webapi port is in use by another process

### ISSUE THREAD

**Issue by lhernandez-free** [iotaledger/goshimmer#345]
## Bug description

If gosimmer process start whent webapi port is ocuped by another process, non error is reported en logs, but web server and other process start correctly, except, webapi process

## GoShimmer version

0.1.3

- GoShimmer version:

virtual pc 

What hardware are you using?

- Operating system:
- RAM:2 GB
- Number of cores: 2
- Device type: intel

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1. Start goshimmer with webaopi port ocuped by other process
2. 
3. 

## Expected behaviour

some log reporting de issue

## Actual behaviour

No error log reported
No access to api

## Errors

Non error reported, that's the problem

**Comment by Wollac** [comment]
Fixed in `develop`
