### ISSUE TITLE
Terminate GoShimmer if it is started without a config file

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/goshimmer#355]
Let GoShimmer exit with a message saying that it must be started with a configuration. For scenarios where a config file is not needed, like for example the integration tests, GoShimmer can be started with a flag so it skips the config availability check and proceeds running.

**Comment by lzpap** [comment]
The logic that currently handles the absence of configuration file is in hive.go: https://github.com/iotaledger/hive.go/blob/dbc13ea3f90c8874c0b93925ac9ad2aa265cc423/parameter/parameter.go#L53-L62

It won't return an error when no config file is present, it sets the default config values from the defaults of the flags from all the packages: https://github.com/iotaledger/hive.go/blob/dbc13ea3f90c8874c0b93925ac9ad2aa265cc423/parameter/parameter.go#L43

My question: should we return an error in this case as well, and handle it in goshimmer to shut down the node with a warning `no config file present`?https://github.com/iotaledger/goshimmer/blob/f04c22b2f61ea461e7e786e77718f96d23dac421/plugins/config/plugin.go#L60-L63 
We could always bypass this with an additional command line flag for test scenarios.

Another, bit hacky way would be to check here if the viper instance has a certain key set in its `config` map with `Node.InConfig()`.  This only gets filled when a config file was successfully read.

What do you think @luca-moser ?

**Comment by luca-moser** [comment]
I believe that if you pass `loadDefault` false, `LoadConfigFile` would return an error, so you could catch that in that case. So basically a "skip-config availability check" flag would simply pass true into `LoadConfigFile` while the absence of that flag + the error returned from `LoadConfigFile` indicates that the node should crash since it isn't started a config.
