### ISSUE TITLE
Message layer panics when trying to access shutdown object storage

### ISSUE THREAD

**Issue by capossele** [iotaledger/goshimmer#361]
## Bug description

Message layer panics while closing GoShimmer because it attempts to access an already shutdown object storage.

Should we change the shutdown priority and terminate the Tangle before than the Database?

**Comment by jonastheis** [comment]
Here's a log from an integration test run. [testnodesynchronization-replica_0.log](https://github.com/iotaledger/goshimmer/files/4547492/testnodesynchronization-replica_0.log)
