### ISSUE TITLE
Integration test suites

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/goshimmer#376]
Integration tests:
* Common: @jonastheis 
  * [x] Spin up a network with multiple nodes and shut it down without any errors.
  * [x] Spin up a network with multiple nodes, issue a couple of data messages in order to form a DAG, continue issuing messages, then let another node join the network, let it solidify, then check whether all issued messages are available on all nodes. Then shut down the newly added peer, let it startup again, check that it is in state desynced and then becomes synced again.
* Message layer: @jonastheis 
     * [x] Issue data messages on multiple nodes, then ensure that the messages are available and solid on all nodes before any shutdown routine, then restart the network and check the availability of the previously issued messages on all nodes.
* Value layer:  @jkrvivian 
     * [x] Issue value messages on multiple nodes, then ensure that the value messages are available, solid and they cause the same mutations to the ledger on all nodes before any shutdown routine, then shut down the network, then restart the network and check the availability of the previously issued value messages on all nodes and verify that the ledger state is still the same between nodes.
     * [x] Repeat the same as above but issue value messages with colored tokens 
* DRNG layer:
   * [x] Create a network consisting out of DRNG committee members and non-committee members, then check that in the given interval random numbers are published and seen by the non-committee member nodes. @capossele  
* Consensus:
   * [x] Issue valid non-conflicting value messages on multiple nodes, ensure that they cause the same ledger mutations and no conflicts are triggered by any node.
   * [x] Issue conflicting and non-conflicting value messages on multiple nodes, ensure that the conflicting value messages are not taken into account on the ledger state but emit conflicts on all the nodes, then verify that via FPC all the nodes materialize to the same opinions of the transactions of the conflict set. In order to make this work, split the network so there are two partitions both having a partial view of the conflict set, then join them to let them resolve the conflicts.
* Autopeering: @jonastheis 
   * [x] Spin up a network, let the nodes query each other, then split the network into two partitions, then re-join it and make sure that nodes between the two partitions connect to each other. Using pre-made private seeds for the autopeering identity should allow us to pre-compute who should peer with whom.

**Comment by Wollac** [comment]
How about running some integration tests also with `-race` could that be helpful?
