### ISSUE TITLE
Refactor graceful shutdown plugin

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/goshimmer#385]
Since `daemon.Shutdown()` locks until all workers have been terminated, the separate goroutine in the graceful shutdown plugin is unable to report hanging workers and in fact just hangs until `Shutdown()` is done. We should either remove the reporting of the hanging workers and simply do the force os.Exit() termination of the process or find a workaround to still see the hanging workers.

Additionally, we need a function in order to cleanly shutdown the node from within other plugins.

**Comment by Wollac** [comment]
Consider the following to make `GetRunningBackgroundWorkers` available during shutdown:
- replace `lock` with a `RWMutex`
- check all locks whether they are a read or write lock (e.g. `GetRunningBackgroundWorkers` should only read-lock)
- split `shutdown` into to parts:
  1. "stop" that only modifies the worker and not the daemon and can thus have a read lock
  2. "clear" that modifies the daemon and requires a write lock for that

No idea whether it works, but it's worth a try :smile:

**Comment by lzpap** [comment]
@Wollac it seems to be working: https://github.com/iotaledger/hive.go/pull/116
