### ISSUE TITLE
[Proposal] Make builds of Docker containers on architectures != amd64 possible

### ISSUE THREAD

**Issue by antonionardella** [iotaledger/goshimmer#426]
Hello everyone!

**Feature request**
Implement different build files based on architectures, given the fact that at this point in time, it is not possible to build the GoShimmer docker container on other architectures besides **amd64**.

Advantages:
- GoShimmer is installable on different architectures.
- There's a file for gorelease/builds that developers can manipulate for ci purposes, instead of affecting users' dockerfile
- Anyone has a file per architecture and can build with the following command: ```docker build -f Dockerfile.arm64 -t some:tag .```

**Describe the solution you'd like**
Different build files based on architectures like HORNET see: https://github.com/gohornet/hornet/tree/v0.4.0-rc8/docker

**Describe alternatives you've considered**
Inserting the arguments **ARCH** and **HASH** as variables in the Dockerfile and manually use them in scripts to build for **aarch64**.
```
############################
ARG HASH=sha256:fc7e7c9c4b0f6d2d5e8611ee73b9d1d3132750108878517bbf988aa772359ae4
# golang:1.14.0-buster
FROM golang@${HASH} AS build

# Ensure ca-certficates are up to date
RUN update-ca-certificates

# Set the current Working Directory inside the container
RUN mkdir /goshimmer
WORKDIR /goshimmer

# Use Go Modules
COPY go.mod .
COPY go.sum .

ENV GO111MODULE=on
RUN go mod download
RUN go mod verify

# Copy everything from the current directory to the PWD(Present Working Directory) inside the container
COPY . .

# Build the binary
ARG ARCH=amd64 
ENV TARGET_ARCH=${ARCH:+-$ARCH}
RUN CGO_ENABLED=0 GOOS=linux GOARCH=${TARGET_ARCH}} go build
[...]
```
and then build with:

```docker build --build-arg HASH=sha256:944405641f9fb0f322be1dfc4685b916df2de3df54525cf80822f8a0529f636f ARCH=aarch64 --tag goshimmer:0.1.3 .```

This means that the users need to know the hashes of particular images and this is prone to errors. One would also be able to manually insert hashes of non-tested base image versions and make bug triage more difficult.
In addition this makes the support of continuous integration processes difficult to manage.

**Additional context**
I know that at this point the focus is on implementing the modules to get the alphanetwork running.

I just wanted to put this issue here before I forget it, as Nuriel and I are working on preparing the tools, in this case the [GoShimmer Playbook](https://github.com/nuriel77/goshimmer-playbook) to make it possible for the community to install GoShimmer and build nodes, in the user friendlies way possible and including a set of different tools (e.g. dashboard, DRAND, SSL certificates) on different platforms, in our test Raspberry Pi 4.

As of now the Dockerfile of GoShimmer has (from what we assume, security reasons) the hash of the **amd64** golang container hard coded in line 5
https://github.com/iotaledger/goshimmer/blob/v0.1.3/Dockerfile#L5
```FROM golang@sha256:fc7e7c9c4b0f6d2d5e8611ee73b9d1d3132750108878517bbf988aa772359ae4 AS build```

And the architecture to build the binary is also hard coded as **amd64**
https://github.com/iotaledger/goshimmer/blob/v0.1.3/Dockerfile#L26
```RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build```

That would of course mean that it would be necessary to maintain and update the ```sha hash``` in >1 file, based on the supported architectures we want to add.

What are your thoughts about this?
Thanks

**Comment by luca-moser** [comment]
We don't support other archs than amd64 in the near future; will reopen once this might have relevance.
