### ISSUE TITLE
node and NAT issue.

### ISSUE THREAD

**Issue by knight-ryu12** [iotaledger/goshimmer#431]
Seems behind-the-NAT node may fail the sanity test.
it fails to call itself from external address, therefore it fail to start.

It'd be cool if we have someway to disable those sanity test partially or propose more good solution to check.

**Comment by knight-ryu12** [comment]
F.E.; node tries to call EXTIP:14666/tcp, but fails due to "impossible call". but it is false positive.

**Comment by jonastheis** [comment]
This has been addressed already with #259. There is a plugin `PortCheck` that can be disabled if it fails but the ports are correctly configured. Also, we got rid of the hairpinning since that's not supported by some routers. 
It will be part of the upcoming release.

**Comment by knight-ryu12** [comment]
I hope that release come fast.
