### ISSUE TITLE
Shutdown doesn't work properly

### ISSUE THREAD

**Issue by muXxer** [iotaledger/goshimmer#45]
Hi!

If I hit CTRL+C in the terminal, the node starts to shutdown, but somehow hangs. After some time I hit the CTRL+C again... and then it forces the shutdown :man_shrugging: 

![grafik](https://user-images.githubusercontent.com/32371094/61812212-55616980-ae43-11e9-9321-4edbc66391c0.png)

**Comment by hmoog** [comment]
Fixed with 5f7494fbf652e2ad3ecddc7d7d49780d0c73a8a0
