### ISSUE TITLE
Think of 'hiving' parts of the analysis server, making it available to HORNET

### ISSUE THREAD

**Issue by c-mnd** [iotaledger/goshimmer#493]
if there's time or need.

**Comment by c-mnd** [comment]
while HORNET is widely independant, I saw a lot advancements on your repos.
I'm just a HORNET-user, but think of transferring some metric libs to 'hive', getting a benetit for all teams developing tangles.

**Comment by luca-moser** [comment]
We unfortunately don't have time to make the analysis server as abstract to make it also integretable with Hornet.
