### ISSUE TITLE
Tips vary on nodes

### ISSUE THREAD

**Issue by jonastheis** [iotaledger/goshimmer#500]
When starting 4 nodes with a clean database all 4 start to sync as expected. However, the tip count varies widely once they are finished. I haven't further investigated whether this is only a dashboard issue or some potential issue with the tip selector of the message tangle. 

![image](https://user-images.githubusercontent.com/4181434/85106989-770ed080-b20d-11ea-92e7-c719567d6468.png)

**Comment by luca-moser** [comment]
* Let the tips chart on the dashboard use the size of the tip pool instead of the "add/remove" tips event to derive the current tips count. Use metrics.MessageTips() to get the tip pool count.
* In the visualizer make sure to clear a vertex' tip state if another vertex references it.

**Comment by capossele** [comment]
Fixed by #650
