### ISSUE TITLE
General analysis server and metrics adjustments

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/goshimmer#507]
* [ ] Let the analysis server retain finalized vote contexts in such a way, so that they don't get cleaned up by the `Analysis[FPCUpdater]`  right away. Fixing this enables people to see finalized conflicts longer on the analysis server dashboard.
* [x] Make sure that the analysis server reconnect to the MongoDB if it loses the connection.
* [x] Make MongoDB storage completely optional.
* [x] For the local avg. number of rounds to finalize a vote context, keep track of the amount of rounds and finalized conflicts, instead of calculating the amount of rounds from the last avg. number of rounds * finalized conflicts. This so we don't loose precision.
* [x] Make things like MPS and TPS simply ever increasing counters and derive MPS/TPS values solely via Prometheus.
* [x] Make the payload registry also take in names for the different payloads so you can use that to derive the payload count instead of having a switch case per payload type. `plugins/prometheus/tangle.go `

**Comment by capossele** [comment]
Covered with #668
