### ISSUE TITLE
Crash after some hours of runtime [concurrent map iteration and map write]

### ISSUE THREAD

**Issue by svenger87** [iotaledger/goshimmer#53]
Stacktrace:

https://gist.github.com/svenger87/d3ea64c31e3db8f2805481871b26e55a

**Comment by huggre** [comment]
I get a similar problem with my 2GB VPS
![goshimmer](https://user-images.githubusercontent.com/18450425/61937320-e3963680-af8e-11e9-9779-61ca8e6a1441.png)

**Comment by svenger87** [comment]
> I get a similar problem with my 2GB VPS, no spamming
> ![goshimmer](https://user-images.githubusercontent.com/18450425/61937320-e3963680-af8e-11e9-9779-61ca8e6a1441.png)

Check the beginning of the stacktrace. If it begins with concurrent map iteration it might be the same.
