### ISSUE TITLE
Decide on a good PoW difficulty

### ISSUE THREAD

**Issue by Wollac** [iotaledger/goshimmer#540]

**Comment by luca-moser** [comment]
To give some notion on a Ryzen 3700X with 16 workers on 260 bytes:

| Workers | Difficulty | Time          |
| ------- | ---------- | ------------- |
| 16      | 20         | 60s           |
| 16      | 21         | 132.554072ms  |
| 16      | 22         | 679.292736ms  |
| 16      | 23         | 2.076173658s  |
| 16      | 24         | 5.225096922s  |
| 16      | 25         | 5.305398877s  |
| 16      | 26         | 9.316807244s  |
| 16      | 27         | 26.288014651s |

Perhaps we should consider using 24 as the default?

**Comment by capossele** [comment]
24 looks too much imo. Let's imagine we want to try a dummy double spend on a simple VM and we should end up already with a time between each other of more than the avg network delay

**Comment by Wollac** [comment]
Those number look a bit strange. Discounting for stuff like thermal throttling, the average times should exactly double with every step.
To give another baseline, on an i7-8550U laptop, it takes on average 196 ms for difficulty=20 (with 8 Workers).
For 24 this would equal to something like 3.13 s.

**Comment by luca-moser** [comment]
Lets leave it at 22 and use 1 worker.
