### ISSUE TITLE
Messages no longer get solid once a node is restarted (At least according to the visualizer)

### ISSUE THREAD

**Issue by acha-bill** [iotaledger/goshimmer#545]
**Describe the bug**
I ran 3 nodes at the same time and attached a spammer to node1. All looks fine. (showing node1 and node2)
<img width="1304" alt="Screenshot 2020-06-24 at 23 37 49" src="https://user-images.githubusercontent.com/57879913/85635118-0a645d80-b675-11ea-94f9-ade52b175f5e.png">

Now, I restarted node2 and messages no longer get solid according to the visualizer. And only showing 1 tip constantly.
<img width="1481" alt="Screenshot 2020-06-24 at 23 38 52" src="https://user-images.githubusercontent.com/57879913/85635210-3bdd2900-b675-11ea-9856-6e0549446d8e.png">

**Expected behavior**
Msgs should solidify on node2. They don't.

**Comment by Wollac** [comment]
Possibly related to https://github.com/iotaledger/goshimmer/issues/525

**Comment by capossele** [comment]
Fixed by #650
