### ISSUE TITLE
Add static peering support

### ISSUE THREAD

**Issue by capossele** [iotaledger/goshimmer#547]
Enables us to write faster integration tests.

1. We could leverage the fact that autopeering and gossip are on separate layers by introducing a manual peered neighbors in the gossip manager. If the autopeering tries to connect with one of them, we can make the gossip to drop that connection and communicate this drop to the autopeering (clearly by keeping up the manual peered connection)
2. These 2 separated neighborhoods should be transparent from the communication primitive perspective
3. We could decouple the neighbor selection part in Goshimmer so that we could only enable the peer discovery and the manual peering to achieve both deterministic topology as well as network knowledge for FPC

Implementation details:
1. Make it possible to turn off the neighbors selection in the autopeering plugin via configuration (`configureEvents()` function)
2. Add a separate list for manual neighbors to the gossip manager, replicate all logic from autopeering neighbors list (existing) to the manual neighbors list (new). The only exception is events from the autopeering layer don't affect the manual neighbors list (new). 
3. Make it possible to set manual peers in the gossip manager via configuration.

**Comment by luca-moser** [comment]
Add web API methods to:
* Add a peer
* Disconnect/Remove a peer

**Comment by jkrvivian** [comment]
Merged in [v0.5.8](https://github.com/iotaledger/goshimmer/releases/tag/v0.5.8).
