### ISSUE TITLE
Spammer API: TPS parameter not working

### ISSUE THREAD

**Issue by StefanoCore** [iotaledger/goshimmer#57]
Currently, calling the spammer with a specific TPS parameter is not working: the spammer keeps sending 1000 TPS even if i call: 

`
curl localhost:8080/spammer?cmd=start&tps=5
`

It looks that request.Tps is always read as equal to ZERO, even if a tps=20 parameters is sent through the GET request.
Probably, the convertion from STRING to INT of the TPS parameter in the GET request is missing (or not working?).

![image](https://user-images.githubusercontent.com/10340922/61994776-41a24700-b07f-11e9-930e-ede1aa8d1f9e.png)

I did a test in order to see what happens if i attach a word instead of a number to the TPS parameter:
`curl localhost:8080/spammer?cmd=start&tps=test`

The node start spamming with 1000 TPS.

**Comment by StefanoCore** [comment]
Wrapping the curl call into single quotes, the spammer correctly receive the TPS parameter:
`curl 'my-iota-node.com:8080/spammer?cmd=start&tps=10'
`

![image](https://user-images.githubusercontent.com/10340922/62010031-d0898f00-b165-11e9-84a8-70ad50fb8d80.png)

**Comment by Wollac** [comment]
:ok_hand:
