### ISSUE TITLE
[GoShimmer Wiki] Minor formatting

### ISSUE THREAD

**Issue by antonionardella** [iotaledger/goshimmer#573]
**Describe the bug**
The [Setup up a GoShimmer node (Joining the GoShimmer testnet)](https://github.com/iotaledger/goshimmer/wiki/Setup-up-a-GoShimmer-node-(Joining-the-GoShimmer-testnet)) wiki page contains commands with `>` e.g.:

```
$ sudo apt-get install \
>     apt-transport-https \
>     ca-certificates \
>     curl \
>     gnupg-agent \
>     software-properties-common
```

[Here the corrected version of that wiki](https://github.com/antonionardella/goshimmer/wiki/Setup-up-a-GoShimmer-node-(Joining-the-GoShimmer-testnet)) page, as I cannot fork/push or make a PR for Wiki pages.

**Comment by luca-moser** [comment]
Thanks
