### ISSUE TITLE
GoShimmer node crashed overnight

### ISSUE THREAD

**Issue by StefanoCore** [iotaledger/goshimmer#58]
The node running on my VPS crashed overnight, apparently during an auto-peering action (after almost a full-day of correct operations).
I'm running a Go compiled version of the node (not a docker version).

Following the suggestion of Muxxer on Discord, i upload:
1. Print-screen of the error i get from Journalctl:
![image](https://user-images.githubusercontent.com/10340922/62004939-335e3480-b12c-11e9-8f7c-9980f5044583.png)

2. The commit reference of the node version i'm running:
`commit 895dfc09ce3ff57ef2c53d78000f77a6ee67fcbc`

![image](https://user-images.githubusercontent.com/10340922/62004947-52f55d00-b12c-11e9-86f7-090544e74128.png)

Any other information or log file required?

**Comment by hmoog** [comment]
Fixed in 9eaead509e7f1b49b0018ba58f38b7a9c12f2cde
