### ISSUE TITLE
Node status incorrect in API Info

### ISSUE THREAD

**Issue by centercirclesolutions** [iotaledger/goshimmer#616]
## Bug description

The {IP}:8080/info API call sometimes will show the incorrect node status. (Seems like it's delayed)
Graphana also shows incongruent info as well

*Note: Ideally this status needs to be on the dashboard*

## GoShimmer version

2.0 (observed) 2.1 (observed)

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.

1. Start Node or let it go out of sync then observe API status

**Comment by luca-moser** [comment]
Note for GoShimmer team: Make sure that the "synced" atomic boolean is reset correctly every time the sync state actually changes.

**Comment by capossele** [comment]
Fixed by #650
