### ISSUE TITLE
[Prometheus] Uptime

### ISSUE THREAD

**Issue by antonionardella** [iotaledger/goshimmer#617]
## Description

Be able to get uptime from prometheus to show in Grafana

## Motivation

Grafana monitoring and alerts

## Are you planning to do it yourself in a pull request?

No.

**Comment by luca-moser** [comment]
Simply set the `prometheus.processMetrics` to `true` to be able to access the `process_start_time_seconds` metric to calculate the uptime. Something like `time() - process_start_time_seconds`.
