### ISSUE TITLE
[GoShimmer] Make node ID and publicKey persistent

### ISSUE THREAD

**Issue by antonionardella** [iotaledger/goshimmer#618]
## Description

Using the docker container the `identityID` and `publicKey` are changed every time the container is restarted.

## Motivation

To maintain a node identity.

## Are you planning to do it yourself in a pull request?

No.

**Comment by capossele** [comment]
identityID and publicKey are stored in the mainnetdb. So if you always mount that volume you should be able to reuse the previous ones. Alternatively, you can create your own seed (e.g., `openssl rand -base64 32`) and load that (with the appropriate prefix) in the config.json under the field `autopeering.seed`.
