### ISSUE TITLE
Windows node shows wrong database size

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/goshimmer#626]
## Bug description

On my Windows GoShimmer node Grafana shows me a Database size of 2.539GB. That is way to big, if i compare it with other linux nodes.
If i check the folder size of `mainnetdb` it is also around 2GB. But why is it so big on Windows?

`ls -r | measure -s Length` shows a size of 2.662GB

## GoShimmer version

- GoShimmer version: v0.2.1

## Hardware specification

What hardware are you using?

- Operating system: Windows 10 Pro 2004
- RAM: 4GB
- Number of cores: 4
- Device type: Lattepanda V1

**Comment by luca-moser** [comment]
BadgerDB allocates vlog files of 2GB in size as a workound under Windows. See https://github.com/dgraph-io/badger/issues/1126#issuecomment-557461324
