### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by svenger87** [iotaledger/goshimmer#633]
## Bug description

Crash happened several times on my RPI4
OS is Raspberry OS 64 bit.

## GoShimmer version

Self compiled 0.2.1 from master branch with go 1.14.4

## Hardware specification

- Operating system: Raspberry Pi OS 64 bit
- RAM: 4G
- Number of cores: 4
- Device type: Raspberry Pi 4

## Expected behaviour

No recurring crash

## Actual behaviour

Crash after some hours. 

## Errors
See attachment
[error.log](https://github.com/iotaledger/goshimmer/files/4890011/error.log)

**Comment by TeeVeeEss** [comment]
Other Hardware/OS (VPS, Ubuntu 18.04 LTS), same Pollen version, same behavior: SIGSEV after a few hours, see logfile.
[sigsev_pollen.log](https://github.com/iotaledger/goshimmer/files/4908886/sigsev_pollen.log)
