### ISSUE TITLE
Visualizer should load old transactions until limit is reached

### ISSUE THREAD

**Issue by mstrewe** [iotaledger/goshimmer#634]
## Description

I think it is a good idea when the visualizer of the goshimmer dashboard loads the transaction history at the beginning until the limit of visual transactions is reached.

## Motivation

Currently only unconnected transactions come up with many unknown transactions. No tips are shown. Maybe with the history you can see patterns or not normal behavior

## Requirements

Write a list of what you want this feature to do.

1. When visualizer of goshimmer dashboard opened it should load last x transactions. Whit x = limit set in visualizer

## Are you planning to do it yourself in a pull request?

No.

**Comment by omg-its-friday** [comment]
oops
