### ISSUE TITLE
Consider using host network for docker for better performance.

### ISSUE THREAD

**Issue by nuriel77** [iotaledger/goshimmer#645]
## Description

Use host network for goshimmer by default (and in all documentation)

## Motivation
> Host mode networking can be useful to optimize performance, and in situations where a container needs to handle a large range of ports, as it does not require network address translation (NAT), and no “userland-proxy” is created for each port.
[source](https://docs.docker.com/network/host/)

It is known that using the host's network is faster than having docker NAT everything using iptables, especially for services such as webservers or applications that rely heavily on network traffic.

## Requirements

Write a list of what you want this feature to do.

1. Remove all references to "publish/expose" ports
2. Use `--net=host` for Docker cli or `network_mode: "host"` in docker-compose
 

## Open questions (optional)

Alternatively, just advise users about this point. I understand that it may not be that important at this stage when there's not much traffic, but is a good thing to take in to account for the future.

## Are you planning to do it yourself in a pull request?

No.

**Comment by luca-moser** [comment]
We will make a note on the wiki page about using `network_mode: "host"` and that then the user has to take care of adjusting the hostnames and iptables themselves. We don't want to encourage it as the current setup seems to be simpler.
