### ISSUE TITLE
Analysis Server Refactor vol 2 - FPC, Metrics

### ISSUE THREAD

**Issue by lzpap** [iotaledger/goshimmer#668]
- Tag and organize collected data according to network version in server:
   - [ ] FPC
   - [ ] Metric
- Send analysis data from server to dashboard that contains network version: 
   - [ ] FPC 
   - [ ] Metric
- Visualize analysis data in dashboard (frontend) for different network versions:
   - [ ] FPC Heartbeat
   - [ ] Metric Heartbeat

**Comment by luca-moser** [comment]
FPC rekt
