### ISSUE TITLE
Fix all linter warnings

### ISSUE THREAD

**Issue by luca-moser** [iotaledger/goshimmer#678]
Install reviewdog locally (https://github.com/reviewdog/reviewdog) and let it run with the same rules as defined in the `.golangci.yml` file (in the repo root).

**Comment by Wollac** [comment]
I don't think there is any need to install reviewdog. https://github.com/golangci/golangci-lint is sufficient and much easier to install locally. Currently, in our action we are using `golangci-lint:v1.24`, but it might also make sense to update https://github.com/reviewdog/action-golangci-lint (and thus the golangci version).
