### ISSUE TITLE
explorer message view not working

### ISSUE THREAD

**Issue by mstrewe** [iotaledger/goshimmer#684]
## Bug description

Explorer shows blank when clicking on a message id

## GoShimmer version

Current Develop on 1bfa13b21130c78b214c08bd81333be2a3a8e970

- GoShimmer version:

Hetzner vps cx21, linux laptop (arch linux 64 bit), chromium browser 84.0.4147.89

## Steps To reproduce the bug

1. go to /explorer 
2. wait for a new message id comming up
3. click on that id
4. e.g. /explorer/message/55sA3mCdBG9oeTVHus51YbaaFtdbQVSgFmaG3YPoKX7iQz25fXv4dinGLoxnfDH7CCddaMyfiqex1UKzBjJGcTcn not loading anything

## Expected behaviour

Describe what you expect to happen.

## Actual behaviour

message view should load

## Errors

![image](https://user-images.githubusercontent.com/15155589/88563261-13f53280-d032-11ea-8866-cd9f2762eb34.png)

**Comment by mstrewe** [comment]
btw. Adress view is working.

**Comment by lzpap** [comment]
@mstrewe #682 solves this issue.
