### ISSUE TITLE
Bug in cli-wallet

### ISSUE THREAD

**Issue by Dr-Electron** [iotaledger/goshimmer#703]
## Bug description

There is a letter in the BALANCE column if i run `cli-wallet balance`

## GoShimmer version

- GoShimmer version: v0.2.3

## Steps To reproduce the bug

1.  Create new seed: `.\cli-wallet init`
2. Request funds: `.\cli-wallet request-funds`
3. Get balance: `.\cli-wallet.exe balance`

## Expected behaviour

There shouldn't be letters in the BALANCE column

## Errors

Paste any errors that you see, including logs, errors, or screenshots.
![grafik](https://user-images.githubusercontent.com/61637085/90036963-e95ad900-dcc3-11ea-9204-3116aaecf674.png)

**Comment by hmoog** [comment]
That is actually not a bug but the "Symbol" of the coin.

**Comment by Dr-Electron** [comment]
A ok. But that wasn't there before. Do you know when is was added? Because i will have to update my wrapper Wallet.
Thanks four your clarification
