### ISSUE TITLE
Add address option for all port bindings

### ISSUE THREAD

**Issue by nuriel77** [iotaledger/goshimmer#74]
For any listener (e.g. zeromq, dashboard, spammer etc), not only allow to configure the port on the command line, but also the address.

Perhaps, instead of calling it port, just take an entire argument called "bind" something like: `-dashboard-bind-address` which accepts the common syntax with go applications:
`:8080` which means `0.0.0.0:8080`, or user can bind to any IP: `10.20.30.10:8080` etc...

This way a user can choose to which interface to bind any of the services (for example when having multiple interfaces)
Or, should a user want to bind to localhost in order to reverse proxy to any of the services, then having this option allows to bind to 127.0.01.

If support for IPv6 can also be addressed it would be really nice as well.

**Comment by Wollac** [comment]
Will be fixed with https://github.com/iotaledger/goshimmer/pull/172
