### ISSUE TITLE
Pending Mana Predictor

### ISSUE THREAD

**Issue by lzpap** [iotaledger/goshimmer#797]
A tool to predict how much pending mana would be generated by spending an output.
Since mana 2 uses the concept of pending mana, it would be great to estimate (calculate) how much `base mana 2` (=pending mana) is pledged to a node when the selected outputs are spent.
Pending mana is calculated as: `output.Balance * (1 - e^(-decay*(now - output.TimeStamp)))`, therefore it depends on the `decay` factor and when the output was generated.

- Add node API endpoint to query pending mana of outputs based on `outputID`,
- Incorporate pending mana into pollen wallet. Since outputs are already fetched in wallet, pending mana calculation can happen locally. In this case, used `decay` factor of the network should be accessible from `/info` endpoint.
- When displaying an output in the explorer of a node, add info about pending mana.

**Comment by acha-bill** [comment]
>Incorporate pending mana into pollen wallet. Since outputs are already fetched in the wallet, pending mana calculation can happen locally. In this case, used decay factor of the network should be accessible from /info endpoint.

The outputs are stored locally in the wallet, however, we still need to query the API for /info and /transaction to get the timestamp.
So calculating this locally is not worth it imo. We should query the API.
