### ISSUE TITLE
Mana storages hang on shutdown

### ISSUE THREAD

**Issue by acha-bill** [iotaledger/goshimmer#801]
Calling shutdown on mana storages hangs. Causing app to not shut down in the time limit.

```
func shutdownStorages() {
	for vectorType := range baseManaVectors {
		storages[vectorType].Shutdown()
	}
}
```

Currently, this is commented out.

```
// TODO: causes plugin to hang
// shutdownStorages()
```

**Comment by lzpap** [comment]
same as #749

**Comment by acha-bill** [comment]
Can't reproduce this again. @lzpap can you?
Else we close this.

**Comment by lzpap** [comment]
@acha-bill I will try. In the meantime, let's think about what shutdown priority should the mana plugin has. Why is it `PriorityTangle` at the moment?

**Comment by acha-bill** [comment]
My thinking was that we want to persist mana stuff successfully and so it should have similar priority to the database.
On the other hand, since we rely on the tangle, then it makes sense to shut it down if the tangle also shuts down. 

I went with the tangle.

**Comment by lzpap** [comment]
I changed the  priority to `PriorityMana` that is just below `PriorityTangle`:
```
const (
	// PriorityDatabase defines the shutdown priority for the database.
	PriorityDatabase = iota
	// PriorityFPC defines the shutdown priority for FPC.
	PriorityFPC
	// PriorityMana defines the shutdown priority for mana.
	PriorityMana
	// PriorityTangle defines the shutdown priority for the tangle.
	PriorityTangle
	// PriorityMissingMessagesMonitoring defines the shutdown priority for missing message monitor.
	PriorityMissingMessagesMonitoring
	// PriorityFaucet defines the shutdown priority for the faucet.
```
I also enabled `leakDetention` in the object storage, like we have for the value tangle.
I still see the hanging of the mana storages on shutdown, although not so often. Look at this pprof output, taken when the mana storage is being shut down (and hangs):
```
1 @ 0x442ca0 0x453ed0 0x453ebb 0x453b22 0x481024 0x7c07fa 0x7be0b3 0xc074db 0xc099b8 0x9413b4 0x4731c1
#	0x453b21	sync.runtime_Semacquire+0x41								/usr/local/go/src/runtime/sema.go:56
#	0x481023	sync.(*WaitGroup).Wait+0x63								/usr/local/go/src/sync/waitgroup.go:130
#	0x7c07f9	github.com/iotaledger/hive.go/objectstorage.(*ObjectStorage).flush+0x169		/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200910101329-33de3e2e05c6/objectstorage/object_storage.go:924
#	0x7be0b2	github.com/iotaledger/hive.go/objectstorage.(*ObjectStorage).Shutdown+0x32		/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200910101329-33de3e2e05c6/objectstorage/object_storage.go:491
#	0xc074da	github.com/iotaledger/goshimmer/plugins/mana.shutdownStorages+0xaa			/tmp/goshimmer/plugins/mana/plugin.go:206
#	0xc099b7	github.com/iotaledger/goshimmer/plugins/mana.run.func1+0x47				/tmp/goshimmer/plugins/mana/plugin.go:164
#	0x9413b3	github.com/iotaledger/hive.go/daemon.(*OrderedDaemon).runBackgroundWorker.func1+0x33	/go/pkg/mod/github.com/iotaledger/hive.go@v0.0.0-20200910101329-33de3e2e05c6/daemon/daemon.go:118
```
The  `ObjectStorage` tries to flush its cache (`object_storage.go` line 900). It does so by iterating through all of the elements in the cache gathering them and then passing them to the `batchWriter`, which should write and release.  As seen from above, the waitgroup `cachedObjectsEmpty` is never done (object_storage.go:924), which means that somehow the batchwriter doesn't release the cache. Line 152 in `batch_writer.go` is never reached, but why?
@acha-bill  maybe we need someone who is an expert on `objectstorage`
