### ISSUE TITLE
Test Pebble VS BadgerDB

### ISSUE THREAD

**Issue by capossele** [iotaledger/goshimmer#855]
- Merge develop to Pebble branch
- Create a docker image for both Pebble
- Runt the following test for both:

    1.  Spam the network with 1000MPM for 5 minutes with 4 nodes (20K messages)
    2. Restart a node and let it sync

Monitor the RAM usage throughout the entire test and compare

**Comment by capossele** [comment]
Pebble uses half of the memory

**Comment by ivanjaros** [comment]
> Pebble uses half of the memory

what about rw performance?
