### ISSUE TITLE
dRNG Beacons slows down syncing from new db

### ISSUE THREAD

**Issue by TeeVeeEss** [iotaledger/goshimmer#858]
## Bug description

Today I removed my db, probably corrupted by some OS-updates resetting the host before the service was properly shutdown. After the next start I saw quite slow progress in getting synced again, roughly 1 min catch up per 10 seconds. Could it be that the Live feed of the Collective Beacons is slowing the node? Showing those old randomness figures has no function imho.

## GoShimmer version

Which version of GoShimmer are you running?

- GoShimmer version: v0.3.1

## Hardware specification

What hardware are you using?

- Operating system: Arch Linux 64bit / Linux 5.9.11-arch2-1
- RAM: 64 GB
- Number of cores: 8 Dual Core Xeon
- Device type: bare metal

## Steps To reproduce the bug

Explain how the maintainer can reproduce the bug.
(when node is unsynced)
1. Stop Goshimmer
2. remove db
3. Start Goshimmer, watch Syncing progress on the Dashboard

## Expected behaviour

In previous Goshimmer versions the syncing from an empty db was much quicker.

## Actual behaviour

Slow progress of getting synced.

## Errors

None.

**Comment by fljota** [comment]
Same issues with syncing:

sync beacon ..., received from 9DB3j9cWYSuEEtkvanrzqkzCQMdH1FGv3TawJdVbDxkd **is too old**.

even 45+min+ Syncing time is not before 15.11.2020

**Comment by capossele** [comment]
I don't think that showing the randomness (even the old ones) could impact on the performance of the node. Unless you have run some diagnostic specifically for this. Most probably, now the Tangle is getting bigger (we have 3 dRNG committees writing a message every 10s) and that's why you are experiencing a slow sync. When we will add snapshots, this should get way better.

**Comment by TeeVeeEss** [comment]
``du -h /opt/goshimmer/db`` gives ``3.4G`` for my now synced node. That's not a very large db and comparable with the db size of previous goshimmer versions. I merely noted the low MPS during the sync. It's was high (1000+) during the first minutes but then slowed down to around 40 with small peaks of 100+.
But I agree, the snapshot feature will solve this, probably not needed to spent time on debugging this issue, better to spent it on the next version ;)
