### ISSUE TITLE
SyncBeacon throws wrapError 

### ISSUE THREAD

**Issue by iamadamsiwy** [iotaledger/goshimmer#859]
## Bug description
If you activate SyncBeacon and  "syncbeacon": { "broadcastInterval": 30  }, syncbeacon/plugin.go:73 throws error

## GoShimmer version

- GoShimmer version: 0.3.1

## Hardware specification

- Operating system: Win 10 WSL Ubuntu 20.04
- RAM: 32GB
- Number of cores: 8
- Device type: WSL

## Steps To reproduce the bug

1. enable SyncBeacon
2. "broadcastInterval": 30 in config.json
3. launch ./goshimmer

## Expected behaviour

INFO Output every 30sec from SyncBeacon

## Actual behaviour

WARN SyncBeacon in DEBUG Console

## Errors

Paste any errors that you see, including logs, errors, or screenshots.

 WARN    SyncBeacon      syncbeacon/plugin.go:73 error issuing sync beacon: %!w(*xerrors.wrapError=&{can't issue payload 0xc00003dd60 {[8047291 11973073 12928631]}})

**Comment by capossele** [comment]
That log shows the inability of issuing sync beacons due to a not synced status. If you do not want to follow other nodes and just want to issue beacons, you should also set `--syncbeacon.startSynced=true`
