### ISSUE TITLE
graceful shutdown after error trying to sync clock

### ISSUE THREAD

**Issue by huggre** [iotaledger/goshimmer#889]
Got this log error after the node had been running without any issues for about 24 hours
Looks like the node was able to restart and sync by itself
![image](https://user-images.githubusercontent.com/18450425/102213299-d573ed80-3ed6-11eb-91e8-b264fcaa79cd.png)

**Comment by lzpap** [comment]
hey @huggre, your node was extremely unlucky to get 3 errors in a row trying to get clock sync, but good to know that this can happen.
@jonastheis, what about increasing `maxTries` and introducing a slight delay inbetween retries? Also, we should print the error returned by `FetchTimeOffset`. Going thorugh the additional notes at [ntp website](https://www.ntppool.org/en/use.html) it might be wise not to shut down the node, or in the future setting up our own time server(s) for more reliability.

**Comment by jonastheis** [comment]
We're not shutting down a node anymore since https://github.com/iotaledger/goshimmer/pull/1275 if it can't sync the clock.
