### ISSUE TITLE
Enable caching for integration tests

### ISSUE THREAD

**Issue by jonastheis** [iotaledger/goshimmer#890]
If we enable [caching](https://docs.github.com/en/free-pro-team@latest/actions/guides/caching-dependencies-to-speed-up-workflows) via any of [these options](https://dev.to/dtinth/caching-docker-builds-in-github-actions-which-approach-is-the-fastest-a-research-18ei) we should be able to speed up at least the pulling of dependencies and building by a large margin. 

This already takes a little bit longer than 3min.

![image](https://user-images.githubusercontent.com/4181434/102218229-92fde100-3ed5-11eb-888a-3adf7ab18c69.png)

**Comment by georgysavva** [comment]
It seems that the article that you mentioned is a bit old. 
Here are the official docket GH actions to achieve image layers caching via Github caching:
https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md
And complete third-party article as a bonus: 
https://evilmartians.com/chronicles/build-images-on-github-actions-with-docker-layer-caching
I will try to pull this off.

**Comment by georgysavva** [comment]
@capossele Why did we close this issue?

**Comment by capossele** [comment]
My bad, I thought we were done with this. I'll reopen it

**Comment by georgysavva** [comment]
After running several benchmarks it turned out that docker layer caching doesn't give any performance benefit due to the fact that we can not cache the Go build. So we should get back this when they fix that in moby/buildkit#1512 
@jonastheis
