### ISSUE TITLE
Clean up zero values from mana vectors

### ISSUE THREAD

**Issue by lzpap** [iotaledger/goshimmer#907]
## Description

Both `Access` and `Consensus` mana vectors use exponential moving averages to arrive at the effective ("usable") mana value of a node. As a consequence, when base mana values become zero, the related effective mana values tend to zero with an exponentially decreasing function, but their value will never become exactly `0`.

 - Find a suitable value close to zero `minimumEffectiveMana` at which the effective value is considered practically zero, and the entry can be removed from the base mana vector.
 - Implement a background worker that periodically cleans up the vectors if their effective mana value drops below `minimumEffectiveMana`.

**Comment by acha-bill** [comment]
IMO it is preferable to say that we know a node and that its mana is `0.001` (for example), rather than returning `ErrNodeNotFoundInBaseManaVector` when we clearly know it.

**Comment by lzpap** [comment]
If we never remove nodes that have `0` mana, the mana vector size will just grow and grow and grow... what's the point of keeping them in memory/database if they have no mana?
 - What is the use case for saying yeah, this node used to have mana some time ago bc it is in the vector, but it doesn't have it now? We don't even know when and how much it had without looking into the events. Events could be exported into csv for historical analysis reasons, so I think it is covered there.

**Comment by acha-bill** [comment]
consensus mana over time (using current mana values) for pledge and revoke.
![points](https://user-images.githubusercontent.com/57879913/106067064-2abe3400-60fe-11eb-99d9-a39d7bd5208c.png)


It takes about 6 hours for effective mana to start moving after a pledge.
It could arrive that when the ticker ticks, mana was just pledged to the node but it wouldn't take effect until 6 hours have passed. So deleting the node from the vector is not right **as it still has baseMana**. `minimumEffectiveMana` is not enough.

As we revoke, we reduce `baseMana1`. So we can safely delete when we have reached `minEffectiveMana` a `minBaseMana2`

___
access mana over time (using current mana values). The second spike is another pledge.

![points](https://user-images.githubusercontent.com/57879913/106066663-80461100-60fd-11eb-8bc1-2c789a320195.png)

As above, we should check for a `minBaseMana1` as well.

**Comment by acha-bill** [comment]
A suitable value for `minimumEffectiveMana` and `minBaseMana2` is `0.001`. I'm unsure about how this value affects other modules ATM.

FYI, the min life span of a node in the access mana vector is about 85hrs. i.e it takes about 85hrs for even `1 access mana` to drop to `0.001`. (`minimumEffectiveMana` and `minBaseMana2`)
![points](https://user-images.githubusercontent.com/57879913/106106447-d474e380-6145-11eb-93b0-0164041079a0.png)

For consensus mana, it's about 40hrs after full revoke.
![points](https://user-images.githubusercontent.com/57879913/106107501-4f8ac980-6147-11eb-864d-2d6542f24b9f.png)

**Comment by lzpap** [comment]
> consensus mana over time (using current mana values) for pledge and revoke.
> ![points](https://user-images.githubusercontent.com/57879913/106067064-2abe3400-60fe-11eb-99d9-a39d7bd5208c.png)
> 
> It takes about 6 hours for effective mana to start moving after a pledge.
> It could arrive that when the ticker ticks, mana was just pledged to the node but it wouldn't take effect until 6 hours have passed. So deleting the node from the vector is not right **as it still has baseMana**. `minimumEffectiveMana` is not enough.
> 
> As we revoke, we reduce `baseMana1`. So we can safely delete when we have reached `minEffectiveMana` and `minBaseMana2`
> 
> access mana over time (using current mana values). The second spike is another pledge.
> 
> ![points](https://user-images.githubusercontent.com/57879913/106066663-80461100-60fd-11eb-8bc1-2c789a320195.png)
> 
> As above, we should check for a `minBaseMana1` as well.

Indeed, we should check for the base value as well, I forgot to add it there.

> It takes about 6 hours for effective mana to start moving after a pledge.

@acha-bill how did you plot the graphs? From grafana? This is not the thing that should happen. As soon as the base value jumps to 100 on the first figure, the effective value should start growing and reach half value (50 in this case) in 6 hours.

I assume you plotted this from grafana while setting the mana coefficients, right? That would explain why you see the 6 hour "delay" when the graph starts, but not when revoke happens at `t=40`.

**Comment by acha-bill** [comment]
> how did you plot the graphs?

using `gonum.org/v1/plot`

Here's the code:
```
start := time.Now()
// pledge 100 mana
// get eff mana for every hour up to 40 hours from `start` to get the pledge curve
for i := 0; i < 40; i++ {
    _ = bmv.UpdateAll(start)  // update base mana with the current hour
    bm := bmv.GetBaseMana(inputPledgeID1) //helper here for testing. Does NOT update
    require.NotNil(t, bm)
    pts[i].X = float64(i)
    pts[i].Y = bm.EffectiveBaseMana2
    start = start.Add(1 * time.Hour) // go 1 more hour.
}

// revoke 100 mana
// do the same above for the next 60 hours to get the revoke curve
```

>This is not the thing that should happen. As soon as the base value jumps to 100 on the first figure, the effective value should start growing and reach half value (50 in this case) in 6 hours.

That's what I see.
