### ISSUE TITLE
Number of tips per node and local knowledge of each node in Prometheus

### ISSUE THREAD

**Issue by alreiff** [iotaledger/goshimmer#921]
Hi everyone,

I think it would be really interesting to have the following data in Prometheus.
- The number of tips belonging to each node (every 5s).
- The knowledge of each node regarding the number of tips of the neighboring nodes (every 5s).
- Also the time/average time for each node to see its own tips to be validated (every 5s).

I hope my suggestions are useful. 

Alexandre

**Comment by lzpap** [comment]
hey @alreiff ,
> The knowledge of each node regarding the number of tips of the neighboring nodes (every 5s).

Is this the subset of the first point? Considering only neighboring nodes from the list of tips?

> Also the time/average time for each node to see its own tips to be validated (every 5s).

What is the definition of `seeing its tips validated` ?

**Comment by alreiff** [comment]
> hey @alreiff ,
> 
> > The knowledge of each node regarding the number of tips of the neighboring nodes (every 5s).
> 
> Is this the subset of the first point? Considering only neighboring nodes from the list of tips?
> 
Not really right. Because a node will have delayed vision of the Tangle. So every node will have a different vision of the tips of the other nodes.

> > Also the time/average time for each node to see its own tips to be validated (every 5s).
> 
> 

What is the definition of `seeing its tips validated` ?
Sorry,  how long a tip of node I is validated.

**Comment by capossele** [comment]
| LocalNodeID | MsgID | IssuerID | issuanceTimestamp | ArrivalTimestamp | SolidTime | FirstChildBasedonIssuanceTimestamp( MsgID | IssuerID | issuanceTimestamp | ArrivalTimestamp | SolidTime)  |  FirstChildBasedonArrival/SolidTimestamp( MsgID | IssuerID | issuanceTimestamp | ArrivalTimestamp | SolidTime) |

**Comment by lzpap** [comment]
+ API to trigger plugin that extracts above information from the database and saves it into a `.csv`
