### ISSUE TITLE
Valucide aftermath

### ISSUE THREAD

**Issue by jonastheis** [iotaledger/goshimmer#972]
- [x] explorer display issues with transaction 
- [x] adjust sendTransactionByJson  @capossele 
- [x] Check transaction time before issuing a Transaction @jonastheis 
- [x] Scheduler persistence to enable nodes restarting @capossele 
- [x] test: Memory during heavy syncing with big DB
- [x] Fix GUI wallet @capossele 
- [x] Grafana: add MPS storing, scheduling, solidification @lzpap 
- [x] Validate transaction before sending it @jkrvivian 

---------

- [x] Dashboard: add MPS storing, scheduling, solidification
- [x] Upgrade to Go 1.16 @capossele @Wollac to review (Later)
- [x] Grafana and dashboard should show actual memory consumption and be consistent @lzpap @jonastheis (Later) take a look at: https://golang.org/pkg/runtime/metrics/

**Comment by jkrvivian** [comment]
Close by #1160
